#![allow(non_snake_case)]

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct CreepWaveData {
    pub Path: Vec<PathJD>,
    pub Creep: Vec<CreepJD>,
    pub CheckPoint: Vec<CheckPointJD>,
    pub Tower: Vec<TowerJD>,
    pub CreepWave: Vec<CreepWaveJD>,
    /// One-based path indices generated by an optional map `SelectSpawnPath` callback.
    #[serde(default)]
    pub SpawnPathSelections: Vec<Vec<usize>>,
    /// 初始小兵放置。主要供 stress 場景在載入時直接建立大量 render-backed creeps，
    /// 避免透過 wave cadence 慢慢出怪而量不到目標 entity 數。
    #[serde(default)]
    pub InitialCreeps: Vec<InitialCreepJD>,
    /// 初始建物放置（引用 `Tower` 模板，指定位置/陣營/是否為基地）
    #[serde(default)]
    pub Structures: Vec<StructureJD>,
    /// 不可通行多邊形區域（英雄與單位會被擋住；不影響視野/投射物）
    #[serde(default)]
    pub BlockedRegions: Vec<BlockedRegionJD>,
    /// 只阻擋 server 視線的圓形樹木；不影響移動碰撞。
    #[serde(default)]
    pub VisionTrees: Vec<VisionTreeJD>,
    /// 只阻擋 server 視線的簡單多邊形；不影響移動碰撞。
    #[serde(default)]
    pub VisionOccluderPolygons: Vec<VisionOccluderPolygonJD>,
    /// 遊戲模式。未指定視為 "Moba"（MVP_1 沿用行為）。
    /// 可選值："Moba" 或 "TowerDefense"。由 `state/initialization.rs::init_creep_wave`
    /// 轉為 `GameMode` resource 供各 system 查詢。
    #[serde(default)]
    pub GameMode: Option<String>,
    /// Opt-in secure selective-lockstep visual demo descriptor.
    #[serde(default)]
    pub FogDemo: Option<FogDemoJD>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct FogDemoJD {
    pub Rows: usize,
    pub Columns: usize,
    pub Spacing: f32,
    pub OriginX: f32,
    pub OriginY: f32,
    pub VisionRadius: f32,
    pub RememberPolicy: String,
    pub GridUnitTemplate: String,
    pub HeroTemplate: String,
    pub HeroSpawns: Vec<FogDemoHeroSpawnJD>,
    pub PatrolIndexes: Vec<usize>,
    pub PatrolOffset: f32,
    pub PatrolSpeed: f32,
}

impl Default for FogDemoJD {
    fn default() -> Self {
        Self {
            Rows: 0,
            Columns: 0,
            Spacing: 0.0,
            OriginX: 0.0,
            OriginY: 0.0,
            VisionRadius: 0.0,
            RememberPolicy: String::new(),
            GridUnitTemplate: String::new(),
            HeroTemplate: String::new(),
            HeroSpawns: Vec::new(),
            PatrolIndexes: Vec::new(),
            PatrolOffset: 0.0,
            PatrolSpeed: 0.0,
        }
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct FogDemoHeroSpawnJD {
    pub PlayerId: u32,
    pub TeamId: u32,
    pub X: f32,
    pub Y: f32,
}

impl FogDemoJD {
    pub fn validate(&self) -> Result<(), String> {
        const GRID_UNITS: usize = 100;
        const HEROES: usize = 2;
        const PATROLS: usize = 16;
        if self.Rows.checked_mul(self.Columns) != Some(GRID_UNITS) {
            return Err(format!(
                "FogDemo Rows*Columns must equal {GRID_UNITS}, got {}*{}",
                self.Rows, self.Columns
            ));
        }
        if self.HeroSpawns.len() != HEROES {
            return Err(format!(
                "FogDemo HeroSpawns must contain {HEROES}, got {}",
                self.HeroSpawns.len()
            ));
        }
        if self.PatrolIndexes.len() != PATROLS {
            return Err(format!(
                "FogDemo PatrolIndexes must contain {PATROLS}, got {}",
                self.PatrolIndexes.len()
            ));
        }
        for (name, value) in [
            ("Spacing", self.Spacing),
            ("OriginX", self.OriginX),
            ("OriginY", self.OriginY),
            ("VisionRadius", self.VisionRadius),
            ("PatrolOffset", self.PatrolOffset),
            ("PatrolSpeed", self.PatrolSpeed),
        ] {
            if !value.is_finite() {
                return Err(format!("FogDemo {name} must be finite, got {value}"));
            }
        }
        if self.Spacing <= 0.0 || self.VisionRadius <= 0.0 || self.PatrolSpeed < 0.0 {
            return Err(
                "FogDemo spacing/radius must be positive and patrol speed non-negative".into(),
            );
        }
        if !matches!(self.RememberPolicy.as_str(), "LastKnown" | "Forget") {
            return Err(format!(
                "FogDemo RememberPolicy must be LastKnown or Forget, got {}",
                self.RememberPolicy
            ));
        }
        let mut players = std::collections::BTreeSet::new();
        let mut teams = std::collections::BTreeSet::new();
        for hero in &self.HeroSpawns {
            if !hero.X.is_finite() || !hero.Y.is_finite() {
                return Err(format!(
                    "FogDemo hero {} coordinate must be finite",
                    hero.PlayerId
                ));
            }
            players.insert(hero.PlayerId);
            teams.insert(hero.TeamId);
        }
        if players != [1, 2].into_iter().collect() || teams != [1, 2].into_iter().collect() {
            return Err(format!("FogDemo hero bindings must be players/teams 1 and 2, got players={players:?} teams={teams:?}"));
        }
        let unique: std::collections::BTreeSet<_> = self.PatrolIndexes.iter().copied().collect();
        if unique.len() != PATROLS || unique.iter().any(|index| *index >= GRID_UNITS) {
            return Err(format!(
                "FogDemo PatrolIndexes must be 16 unique values in 0..100, got {:?}",
                self.PatrolIndexes
            ));
        }
        if self.GridUnitTemplate.trim().is_empty() || self.HeroTemplate.trim().is_empty() {
            return Err("FogDemo template names must not be empty".into());
        }
        Ok(())
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct InitialCreepJD {
    pub Creep: String,
    pub Path: String,
    #[serde(default)]
    pub PathIndex: usize,
    #[serde(default)]
    pub Faction: Option<String>,
    pub X: f32,
    pub Y: f32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct StructureJD {
    /// 對應 `Tower[*].Name`（模板名稱，用於查 Hp/Range/AttackSpeed/Physic）
    pub Tower: String,
    /// "Player" 或 "Enemy"
    pub Faction: String,
    pub X: f32,
    pub Y: f32,
    /// 是否為基地（擊毀敵方基地＝玩家勝）
    #[serde(default)]
    pub IsBase: bool,
    /// 覆寫該實例的碰撞半徑（未填用預設）
    #[serde(default)]
    pub CollisionRadius: Option<f32>,
}
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct PathJD {
    pub Name: String,
    pub Points: Vec<String>,
}
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct CreepJD {
    /// 產生的 Creep 模板 ID。地圖本地蠕變統計數據在期間被拒絕
    /// Lua 程式碼產生器；執行時間透過 `omoba-template-ids` 解析統計資料。
    pub Name: String,
    /// 舊版純 JSON 欄位。產生的地圖資料忽略了這一點。
    #[serde(default)]
    pub Label: Option<String>,
    #[serde(default)]
    pub HP: f32,
    #[serde(default)]
    pub DefendPhysic: f32,
    #[serde(default)]
    pub DefendMagic: f32,
    #[serde(default)]
    pub MoveSpeed: f32,
    /// 陣營 "Player" / "Enemy"；預設 Enemy。用於 LoL 式雙方出兵
    #[serde(default)]
    pub Faction: Option<String>,
    /// 轉速（度/秒），未填用 90
    #[serde(default)]
    pub TurnSpeed: Option<f32>,
    /// 碰撞半徑（未填用預設 20）
    #[serde(default)]
    pub CollisionRadius: Option<f32>,
}
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct CheckPointJD {
    pub Name: String,
    pub Class: String,
    pub X: f32,
    pub Y: f32,
}
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct TowerJD {
    pub Name: String,
    pub Property: PropertyJD,
    pub Attack: AttackJD,
    /// 轉速（度/秒），未填用 90
    #[serde(default)]
    pub TurnSpeed: Option<f32>,
    /// 碰撞半徑（未填用預設 50）
    #[serde(default)]
    pub CollisionRadius: Option<f32>,
}
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct AttackJD {
    pub Range: f32,
    pub AttackSpeed: f32,
    pub Physic: f32,
    pub Magic: f32,
}
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct PropertyJD {
    pub Hp: i32,
    pub Block: i32,
}
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct CreepWaveJD {
    pub Name: String,
    pub StartTime: f32,
    pub Detail: Vec<DetailJD>,
}
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct DetailJD {
    pub Path: String,
    pub Creeps: Vec<CreepsJD>,
}
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct CreepsJD {
    pub Time: f32,
    pub Creep: String,
}

/// 不可通行多邊形區域（凹/凸皆可）。至少 3 點。
/// 由 generated map data 的 `BlockedRegions` 欄位載入，並於 `state/initialization.rs`
/// 轉為 `comp::BlockedRegions` resource 供移動 tick 查詢。
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct BlockedRegionJD {
    pub Name: String,
    pub Points: Vec<PointJD>,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, Default)]
pub struct PointJD {
    pub X: f32,
    pub Y: f32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct VisionTreeJD {
    pub StableId: u64,
    pub X: f32,
    pub Y: f32,
    pub Radius: f32,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct VisionOccluderPolygonJD {
    pub StableId: u64,
    #[serde(default)]
    pub Name: String,
    pub Points: Vec<PointJD>,
}
