return function(ctx)
  return {
    {
      id = "sniper_mode",
      display_name = "狙擊模式",
      icon = "data/hero1_1.png",
      description = "切換到狙擊模式，增加射程和傷害，但降低攻擊速度和移動速度。",
      ability_type = "toggle",
      target_type = "none",
      cast_type = "instant",
      max_level = 4,
      levels = {
        {
          cooldown = 0.0,
          mana_cost = 0.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 0.0,
          mana_cost = 0.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 0.0,
          mana_cost = 0.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 0.0,
          mana_cost = 0.0,
          cast_time = 0.0,
          range = 0.0,
        },
      },
      extras = {
        range_bonus = {
          100.0,
          200.0,
          300.0,
          400.0,
        },
        damage_bonus = {
          0.15,
          0.25,
          0.35,
          0.45,
        },
        attack_speed_penalty = {
          -0.3,
          -0.3,
          -0.3,
          -0.3,
        },
        move_speed_penalty = {
          -0.5,
          -0.5,
          -0.5,
          -0.5,
        },
        accuracy_bonus = {
          0.1,
          0.1,
          0.1,
          0.1,
        },
      },
    },
    {
      id = "saika_reinforcements",
      display_name = "雜賀援軍",
      icon = "data/hero1_2.png",
      description = "在目標位置召喚雜賀鐵炮兵協助作戰。",
      ability_type = "active",
      target_type = "point",
      cast_type = "instant",
      max_level = 4,
      levels = {
        {
          cooldown = 27.0,
          mana_cost = 90.0,
          cast_time = 0.5,
          range = 800.0,
        },
        {
          cooldown = 26.0,
          mana_cost = 90.0,
          cast_time = 0.5,
          range = 800.0,
        },
        {
          cooldown = 25.0,
          mana_cost = 90.0,
          cast_time = 0.5,
          range = 800.0,
        },
        {
          cooldown = 24.0,
          mana_cost = 90.0,
          cast_time = 0.5,
          range = 800.0,
        },
      },
      extras = {
        summon_count = {
          2.0,
          4.0,
          6.0,
          8.0,
        },
        duration = {
          45.0,
          50.0,
          55.0,
          60.0,
        },
        row_spacing = {
          60.0,
          60.0,
          60.0,
          60.0,
        },
        col_spacing = {
          60.0,
          60.0,
          60.0,
          60.0,
        },
        front_row_distance = {
          120.0,
          120.0,
          120.0,
          120.0,
        },
        formation_radius = {
          100.0,
          100.0,
          100.0,
          100.0,
        },
        gunner_hp = {
          350.0,
          400.0,
          450.0,
          500.0,
        },
        gunner_damage = {
          50.0,
          60.0,
          70.0,
          80.0,
        },
      },
    },
    {
      id = "rain_iron_cannon",
      display_name = "雨鐵砲",
      icon = "data/hero1_3.png",
      description = "被動：普攻命中時以受擊點為中心、朝攻擊方向 90° 扇形 150 半徑對範圍內所有單位造成 15/25/35/45% 攻擊力的真實傷害。",
      ability_type = "passive",
      target_type = "none",
      cast_type = "instant",
      max_level = 4,
      levels = {
        {
          cooldown = 0.0,
          mana_cost = 0.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 0.0,
          mana_cost = 0.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 0.0,
          mana_cost = 0.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 0.0,
          mana_cost = 0.0,
          cast_time = 0.0,
          range = 0.0,
        },
      },
      extras = {
        true_damage_pct = {
          0.15,
          0.25,
          0.35,
          0.45,
        },
        aoe_radius = {
          150.0,
          150.0,
          150.0,
          150.0,
        },
        arc_half_angle_rad = {
          0.7853982,
          0.7853982,
          0.7853982,
          0.7853982,
        },
      },
    },
    {
      id = "three_stage_technique",
      display_name = "三段擊",
      icon = "data/hero1_4.png",
      description = "變身 5 秒：攻擊力 +200%，普攻特效改為連發 3 發子彈（只判定 1 次傷害），身上有紅色變身特效。",
      ability_type = "active",
      target_type = "none",
      cast_type = "instant",
      max_level = 4,
      levels = {
        {
          cooldown = 15.0,
          mana_cost = 80.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 13.0,
          mana_cost = 90.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 11.0,
          mana_cost = 100.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 9.0,
          mana_cost = 110.0,
          cast_time = 0.0,
          range = 0.0,
        },
      },
      extras = {
        duration = {
          5.0,
          5.0,
          5.0,
          5.0,
        },
        atk_bonus_pct = {
          2.0,
          2.0,
          2.0,
          2.0,
        },
        multi_shot_count = {
          3.0,
          3.0,
          3.0,
          3.0,
        },
      },
    },
    {
      id = "flame_blade",
      display_name = "炎刃",
      icon = "data/ability_icons/ability_flame_blade.png",
      description = "往前方揮出一刀，對單體或範圍目標造成大量火焰傷害。",
      ability_type = "active",
      target_type = "point",
      cast_type = "instant",
      max_level = 4,
      levels = {
        {
          cooldown = 10.0,
          mana_cost = 100.0,
          cast_time = 0.0,
          range = 1100.0,
        },
        {
          cooldown = 10.0,
          mana_cost = 120.0,
          cast_time = 0.0,
          range = 1100.0,
        },
        {
          cooldown = 10.0,
          mana_cost = 140.0,
          cast_time = 0.0,
          range = 1100.0,
        },
        {
          cooldown = 10.0,
          mana_cost = 160.0,
          cast_time = 0.0,
          range = 1100.0,
        },
      },
      extras = {
        damage = {
          200.0,
          250.0,
          300.0,
          350.0,
        },
        swipe_radius = {
          100.0,
          100.0,
          100.0,
          100.0,
        },
      },
    },
    {
      id = "fire_dash",
      display_name = "火焰衝擊",
      icon = "data/ability_icons/ability_fire_dash.png",
      description = "往前衝刺，沿路對敵人造成火焰傷害。",
      ability_type = "active",
      target_type = "point",
      cast_type = "instant",
      max_level = 4,
      levels = {
        {
          cooldown = 30.0,
          mana_cost = 80.0,
          cast_time = 0.0,
          range = 900.0,
        },
        {
          cooldown = 30.0,
          mana_cost = 100.0,
          cast_time = 0.0,
          range = 1000.0,
        },
        {
          cooldown = 30.0,
          mana_cost = 120.0,
          cast_time = 0.0,
          range = 1100.0,
        },
        {
          cooldown = 30.0,
          mana_cost = 140.0,
          cast_time = 0.0,
          range = 1200.0,
        },
      },
      extras = {
        damage_per_tick = {
          50.0,
          60.0,
          70.0,
          80.0,
        },
        dash_duration = {
          0.5,
          0.5,
          0.5,
          0.5,
        },
        speed_bonus = {
          2.0,
          2.0,
          2.0,
          2.0,
        },
        dash_width = {
          150.0,
          150.0,
          150.0,
          150.0,
        },
      },
    },
    {
      id = "flame_assault",
      display_name = "炎襲",
      icon = "data/ability_icons/ability_flame_assault.png",
      description = "施展一道巨型火焰，對範圍內敵人造成傷害並暈眩。",
      ability_type = "ultimate",
      target_type = "point",
      cast_type = "instant",
      max_level = 4,
      levels = {
        {
          cooldown = 14.0,
          mana_cost = 120.0,
          cast_time = 0.0,
          range = 700.0,
        },
        {
          cooldown = 14.0,
          mana_cost = 140.0,
          cast_time = 0.0,
          range = 700.0,
        },
        {
          cooldown = 14.0,
          mana_cost = 160.0,
          cast_time = 0.0,
          range = 700.0,
        },
        {
          cooldown = 14.0,
          mana_cost = 180.0,
          cast_time = 0.0,
          range = 700.0,
        },
      },
      extras = {
        damage = {
          200.0,
          300.0,
          400.0,
          500.0,
        },
        stun_duration = {
          0.3,
          0.6,
          0.9,
          1.2,
        },
        radius = {
          500.0,
          500.0,
          500.0,
          500.0,
        },
      },
    },
    {
      id = "matchlock_gun",
      display_name = "火繩銃",
      icon = "data/ability_icons/ability_matchlock_gun.png",
      description = "將武器變身火繩銃，增加攻擊距離與傷害，攻擊時有機率暈眩敵人。持續 45 秒。",
      ability_type = "active",
      target_type = "none",
      cast_type = "instant",
      max_level = 3,
      levels = {
        {
          cooldown = 110.0,
          mana_cost = 260.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 110.0,
          mana_cost = 310.0,
          cast_time = 0.0,
          range = 0.0,
        },
        {
          cooldown = 110.0,
          mana_cost = 360.0,
          cast_time = 0.0,
          range = 0.0,
        },
      },
      extras = {
        duration = {
          45.0,
          45.0,
          45.0,
        },
        range_bonus = {
          700.0,
          800.0,
          900.0,
        },
        damage_bonus = {
          90.0,
          130.0,
          170.0,
        },
        stun_chance = {
          0.87,
          0.87,
          0.87,
        },
        stun_duration = {
          0.1,
          0.2,
          0.3,
        },
      },
    },
  }
end
