return function(ctx)
  return {
    {
      id = "saika_magoichi",
      display_name = "雜賀孫市",
      title = "千里狙擊手",
      background = "雜賀眾的領袖，以精準的遠程射擊聞名於戰國時代",
      abilities = {
        "sniper_mode",
        "saika_reinforcements",
        "rain_iron_cannon",
        "three_stage_technique",
      },
      strength = 18,
      agility = 28,
      intelligence = 16,
      primary_attribute = "agility",
      attack_range = 900.0,
      base_damage = 52,
      base_armor = 1.5,
      base_hp = 580,
      base_mana = 300,
      move_speed = 320.0,
      turn_speed = 180.0,
      level_growth = {
        strength_per_level = 1.8,
        agility_per_level = 3.2,
        intelligence_per_level = 1.6,
        damage_per_level = 2.8,
        hp_per_level = 58.0,
        mana_per_level = 26.0,
      },
    },
    {
      id = "date_masamune",
      display_name = "伊達政宗",
      title = "獨眼龍",
      background = "奧州的霸主，以炎之鬥技與火繩銃聞名",
      abilities = {
        "flame_blade",
        "fire_dash",
        "flame_assault",
        "matchlock_gun",
      },
      strength = 26,
      agility = 22,
      intelligence = 14,
      primary_attribute = "strength",
      attack_range = 250.0,
      base_damage = 60,
      base_armor = 2.5,
      base_hp = 680,
      base_mana = 240,
      move_speed = 310.0,
      turn_speed = 200.0,
      level_growth = {
        strength_per_level = 3.0,
        agility_per_level = 1.8,
        intelligence_per_level = 1.4,
        damage_per_level = 3.2,
        hp_per_level = 68.0,
        mana_per_level = 22.0,
      },
    },
  }
end
