return function(ctx)
  return {
    {
      id = "saika_magoichi",
      display_name = "雜賀孫市",
      title = "千里狙擊手",
      portrait = "data/hero_portraits/hero_saika_magoichi_portrait.png",
      background = "雜賀眾的領袖，以精準的遠程射擊聞名於戰國時代",
      abilities = {
        "sniper_mode",
        "saika_reinforcements",
        "rain_iron_cannon",
        "three_stage_technique",
      },
      strength = 18,
      agility = 28,
      intelligence = 16,
      primary_attribute = "agility",
      attack_range = 900.0,
      base_damage = 52,
      base_armor = 1.5,
      base_hp = 580,
      base_mana = 300,
      move_speed = 320.0,
      turn_speed = 720.0,
      render = {
        render_mode = "model_3d",
        model = "templates/heroes/saika_magoichi/saika_magoichi.fbx",
        texture = "templates/heroes/saika_magoichi/saika_magoichi_mat.png",
        scale = 0.012,
        pitch_offset_deg = -90.0,
        roll_offset_deg = 0.0,
        yaw_offset_deg = -90.0,
        z_offset = 0.0,
        muzzle_bone = "Weapon Ref",
        animation_sources = {
          idle = {
            model = "templates/heroes/saika_magoichi/b01_ani_stand.fbx",
            animation = "Take 001",
            duration_ticks = 80.0,
            ticks_per_second = 30.0,
            timeline_offset_ticks = 66.0,
          },
          idle_2 = {
            model = "templates/heroes/saika_magoichi/b01_ani_stand2.fbx",
            animation = "Take 001",
            duration_ticks = 125.0,
            ticks_per_second = 30.0,
            timeline_offset_ticks = 143.0,
          },
          idle_3 = {
            model = "templates/heroes/saika_magoichi/b01_ani_stand3.fbx",
            animation = "Take 001",
            duration_ticks = 53.0,
            ticks_per_second = 30.0,
            timeline_offset_ticks = 747.0,
          },
          move = {
            model = "templates/heroes/saika_magoichi/b01_ani_run.fbx",
            animation = "Take 001",
            duration_ticks = 23.0,
            ticks_per_second = 30.0,
            timeline_offset_ticks = 394.0,
          },
          attack = {
            model = "templates/heroes/saika_magoichi/b01_ani_attack.fbx",
            animation = "Take 001",
            duration_ticks = 100.0,
            ticks_per_second = 30.0,
            timeline_offset_ticks = 268.0,
          },
          critical = {
            model = "templates/heroes/saika_magoichi/b01_ani_attack.fbx",
            animation = "Take 001",
            duration_ticks = 100.0,
            ticks_per_second = 30.0,
            timeline_offset_ticks = 268.0,
          },
          sniper = {
            model = "templates/heroes/saika_magoichi/b01_ani_stand3.fbx",
            animation = "Take 001",
            duration_ticks = 53.0,
            ticks_per_second = 30.0,
            timeline_offset_ticks = 747.0,
          },
        },
        animations = {
          move = {
            source = "move",
            start_tick = 0.0,
            end_tick = 23.0,
            loop = true,
          },
          attack = {
            source = "attack",
            start_tick = 0.0,
            repeat_start_tick = 10.0,
            impact_tick = 22.0,
            end_tick = 100.0,
            loop = false,
          },
          critical = {
            source = "critical",
            start_tick = 0.0,
            repeat_start_tick = 6.0,
            impact_tick = 22.0,
            end_tick = 100.0,
            loop = false,
          },
          idle = {
            source = "idle",
            start_tick = 0.0,
            end_tick = 80.0,
            loop = true,
          },
          idle_2 = {
            source = "idle_2",
            start_tick = 0.0,
            end_tick = 125.0,
            loop = true,
          },
          idle_3 = {
            source = "idle_3",
            start_tick = 0.0,
            end_tick = 53.0,
            loop = true,
          },
          sniper = {
            source = "sniper",
            start_tick = 0.0,
            end_tick = 53.0,
            loop = true,
          },
        },
      },
      level_growth = {
        strength_per_level = 1.8,
        agility_per_level = 3.2,
        intelligence_per_level = 1.6,
        damage_per_level = 2.8,
        hp_per_level = 58.0,
        mana_per_level = 26.0,
      },
    },
    {
      id = "date_masamune",
      display_name = "伊達政宗",
      title = "獨眼龍",
      portrait = "data/hero_portraits/hero_date_masamune_portrait.png",
      background = "奧州的霸主，以炎之鬥技與火繩銃聞名",
      abilities = {
        "flame_blade",
        "fire_dash",
        "flame_assault",
        "matchlock_gun",
      },
      strength = 26,
      agility = 22,
      intelligence = 14,
      primary_attribute = "strength",
      attack_range = 250.0,
      base_damage = 60,
      base_armor = 2.5,
      base_hp = 680,
      base_mana = 240,
      move_speed = 310.0,
      turn_speed = 200.0,
      level_growth = {
        strength_per_level = 3.0,
        agility_per_level = 1.8,
        intelligence_per_level = 1.4,
        damage_per_level = 3.2,
        hp_per_level = 68.0,
        mana_per_level = 22.0,
      },
    },
  }
end
