//! omb-script-abi — stable ABI contract between omb host and script DLLs.
//!
//! This crate is the **only** thing both the host and all script cdylibs
//! depend on. It must use ONLY `abi_stable` types; no specs, no omb main
//! crate, nothing that would pull engine internals across the FFI boundary.

pub mod ability;
pub mod buff_ids;
pub mod manifest;
pub mod script;
pub mod stat_keys;
pub mod types;
pub mod world;

// Re-export template id newtypes so scripts can `use omb_script_abi::prelude::*;`
// and reference `TOWER_TACK`, `TPL_HERO_SAIKA_MAGOICHI`, etc. without adding
// a separate dependency in every script crate.
pub use omoba_template_ids::{
    AbilityId, BuffId, CreepId, HeroId, ProjectileKindId, SummonId, TowerId,
};

pub mod prelude {
    pub use crate::ability::{AbilityDefFFI, AbilityScript, AbilityScript_TO};
    pub use crate::script::{UnitScript, UnitScript_TO};
    pub use crate::stat_keys;
    pub use crate::types::*;
    pub use crate::world::{GameWorld, GameWorldDyn, GameWorld_TO};
    pub use abi_stable::{
        rstr,
        sabi_trait::prelude::*,
        std_types::{RBox, RNone, ROption, RSome, RStr, RString, RVec},
    };

    // 讓腳本可以方便建這些常用型別不用自己 import
    pub use crate::types::{
        EntityHandle, DamageKind, DamageInfo, Target, PathSpec,
        TowerMetadata, ProjectileSpec, Fixed64, Vec2, Angle,
    };

    // Template ids — newtype + const generated by omoba-template-ids build.rs.
    // Scripts import via `use omb_script_abi::prelude::*;` and reference
    // TOWER_TACK / HERO_SAIKA_MAGOICHI / ABILITY_SNIPER_MODE / BUFF_STUN etc.
    pub use omoba_template_ids::*;
}
