//! 共用 stat key 枚舉 — 對應 Dota 2 MODIFIER_PROPERTY_*（~140 項）。
//!
//! 所有 DLL 腳本透過 `world.add_stat_buff(..., modifiers_json)` 寫入屬性修改；
//! host 端 `UnitStats` helper 聚合並套用到 tick 系統 / damage pipeline。
//!
//! 命名慣例（與 BuffStore 聚合對應）：
//! * `*Bonus` / `*Constant` / `*Stacking` → 加法聚合（`sum_add`）；空為 0
//! * `*Percentage` → 加法聚合後當倍率（乘到 `1 + sum`）
//! * `*Multiplier` → 乘法聚合（`product_mult`）；空為 1
//! * `*Chance` → 觸發機率（0..=1）
//!
//! 分三大 section（見 `StatSection`）：
//! 1. **All**：全單位通用（包含建築物）
//! 2. **NonBuilding**：僅非建築物
//! 3. **Visual**：純視覺 / 前端 pass-through
//!
//! 此檔由 `docs/tools/gen_stat_keys.py` 產生；請勿手改。
//! 新增 variant 請改 generator 後重跑並 commit 兩個檔案。

use abi_stable::StableAbi;

/// StatKey 的三分章節分類（對應 Dota 2 modifier property 的通用性）。
///
/// - `All`：全單位通用（包含建築物）
/// - `NonBuilding`：僅非建築物（有 IsBuilding 標記的實體會跳過）
/// - `Visual`：純視覺／前端 pass-through（不影響遊戲邏輯）
#[repr(u8)]
#[derive(StableAbi, Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum StatSection {
    All = 0,
    NonBuilding = 1,
    Visual = 2,
}

/// StatKey 的聚合方式（對應 BuffStore 的 payload 數值合併規則）。
///
/// - `SumAdd`：`_Bonus` / `_Constant` / `_Stacking` — 多個 buff 的數值直接相加（預設 0）
/// - `SumAddThenMul1Plus`：`_Percentage` — 相加後當倍率係數套用 `(1.0 + sum)`
/// - `ProductMult`：`_Multiplier` — 多個 buff 的數值相乘（預設 1.0）
/// - `Chance`：`_Chance` — 觸發機率 `[0.0, 1.0]`，通常只取最大值或 OR 邏輯
/// - `PassThrough`：視覺 / 覆蓋型（例 `*_override`）— host 直接轉發原值不聚合
#[repr(u8)]
#[derive(StableAbi, Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Aggregation {
    SumAdd = 0,
    SumAddThenMul1Plus = 1,
    ProductMult = 2,
    Chance = 3,
    PassThrough = 4,
}


/// Script ABI 的 stat key 枚舉。
///
/// # SAFETY
/// Variant 順序 = FFI ABI 契約：新增只能 **追加到尾端**，絕不可在中間 insert
/// 或更動 discriminant 值，否則 host 與 script DLL 版本不同步會 UB。
/// **刪除亦禁止**：廢棄 variant 請保留佔位並標 `#[deprecated]`，
/// 避免後續 discriminant 重編號錯位。
/// 每個 variant 顯式寫 `= N` 以鎖定值。
// u16 而非 u8：目前 variant 數 < 256 但留擴充空間（未來若對齊 Dota 2 完整 modifier list 可能超 256）。
#[repr(u16)]
#[derive(StableAbi, Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum StatKey {
    PreattackBonusDamage = 0,
    PreattackBonusDamageProc = 1,
    PreattackBonusDamagePostCrit = 2,
    BaseAttackBonusDamage = 3,
    ProcattackBonusDamagePhysical = 4,
    ProcattackBonusDamageMagical = 5,
    ProcattackBonusDamagePure = 6,
    ProcattackFeedback = 7,
    InvisibilityLevel = 8,
    PersistentInvisibility = 9,
    AttackSpeedBaseOverride = 10,
    FixedAttackRate = 11,
    AttackSpeedBonusConstant = 12,
    CooldownReductionConstant = 13,
    BaseAttackTimeConstant = 14,
    AttackPointConstant = 15,
    DamageOutgoingPercentage = 16,
    TotalDamageOutgoingPercentage = 17,
    SpellAmplifyPercentage = 18,
    HpRegenAmplifyPercentage = 19,
    MagicDamageOutgoingPercentage = 20,
    BaseDamageOutgoingPercentage = 21,
    BaseDamageOutgoingPercentageUnique = 22,
    IncomingDamagePercentage = 23,
    IncomingPhysicalDamagePercentage = 24,
    IncomingPhysicalDamageConstant = 25,
    IncomingSpellDamageConstant = 26,
    EvasionConstant = 27,
    NegativeEvasionConstant = 28,
    AvoidDamage = 29,
    AvoidSpell = 30,
    MissPercentage = 31,
    PhysicalArmorBonus = 32,
    PhysicalArmorBonusUnique = 33,
    PhysicalArmorBonusUniqueActive = 34,
    IgnorePhysicalArmor = 35,
    MagicalResistanceDirectModification = 36,
    MagicalResistanceBonus = 37,
    MagicalResistanceDecrepifyUnique = 38,
    BaseManaRegen = 39,
    ManaRegenConstant = 40,
    ManaRegenConstantUnique = 41,
    ManaRegenPercentage = 42,
    ManaRegenTotalPercentage = 43,
    HealthRegenConstant = 44,
    HealthRegenPercentage = 45,
    HealthBonus = 46,
    ManaBonus = 47,
    ExtraStrengthBonus = 48,
    ExtraHealthBonus = 49,
    ExtraManaBonus = 50,
    ExtraHealthPercentage = 51,
    StatsStrengthBonus = 52,
    StatsAgilityBonus = 53,
    StatsIntellectBonus = 54,
    CastRangeBonus = 55,
    CastRangeBonusStacking = 56,
    AttackRangeBonus = 57,
    AttackRangeBonusUnique = 58,
    MaxAttackRange = 59,
    ProjectileSpeedBonus = 60,
    CooldownPercentage = 61,
    CooldownPercentageStacking = 62,
    CastTimePercentage = 63,
    ManaCostPercentage = 64,
    PreattackCriticalStrike = 65,
    PreattackTargetCriticalStrike = 66,
    CritMultiplier = 67,
    MagicalConstantBlock = 68,
    PhysicalConstantBlock = 69,
    PhysicalConstantBlockSpecial = 70,
    TotalConstantBlockUnavoidablePreArmor = 71,
    TotalConstantBlock = 72,
    AbsorbSpell = 73,
    ReflectSpell = 74,
    DisableAutoattack = 75,
    MinHealth = 76,
    AbsoluteNoDamagePhysical = 77,
    AbsoluteNoDamageMagical = 78,
    AbsoluteNoDamagePure = 79,
    DisableHealing = 80,
    AlwaysAllowAttack = 81,
    OverrideAttackMagical = 82,
    Lifesteal = 83,
    HealReceivedMultiplier = 84,
    UnitStatsNeedsRefresh = 85,
    AccuracyBonus = 86,
    SplashBonus = 87,
    CritBonus = 88,
    SlowFactorOverride = 89,
    SlowDurationBonus = 90,
    AttackSpeedMultiplier = 91,
    MoveSpeedBonusConstant = 92,
    MoveSpeedBaseOverride = 93,
    MoveSpeedBonusPercentage = 94,
    MoveSpeedBonusPercentageUnique = 95,
    MoveSpeedBonusPercentageUnique2 = 96,
    MoveSpeedBonusUnique = 97,
    MoveSpeedBonusUnique2 = 98,
    MoveSpeedAbsolute = 99,
    MoveSpeedAbsoluteMin = 100,
    MoveSpeedLimit = 101,
    MoveSpeedMax = 102,
    TurnRatePercentage = 103,
    Reincarnation = 104,
    RespawnTime = 105,
    RespawnTimePercentage = 106,
    RespawnTimeStacking = 107,
    DeathGoldCost = 108,
    ExpRateBoost = 109,
    BonusDayVision = 110,
    BonusNightVision = 111,
    BonusNightVisionUnique = 112,
    BonusVisionPercentage = 113,
    FixedDayVision = 114,
    FixedNightVision = 115,
    IsIllusion = 116,
    IllusionLabel = 117,
    SuperIllusion = 118,
    SuperIllusionWithUltimate = 119,
    DamageOutgoingPercentageIllusion = 120,
    BountyCreepMultiplier = 121,
    BountyOtherMultiplier = 122,
    PreAttack = 123,
    OverrideAnimation = 124,
    OverrideAnimationWeight = 125,
    OverrideAnimationRate = 126,
    DisableTurning = 127,
    IgnoreCastAngle = 128,
    StunChance = 129,
    StunDuration = 130,
    CritChance = 131,
    AttackStunChance = 132,
    AttackStunDuration = 133,
}

impl StatKey {
    /// 回傳對應的 wire-format 字串（與 Dota 2 modifier property 名稱一致）。
    pub const fn as_str(self) -> &'static str {
        match self {
            StatKey::PreattackBonusDamage => "preattack_bonus_damage",
            StatKey::PreattackBonusDamageProc => "preattack_bonus_damage_proc",
            StatKey::PreattackBonusDamagePostCrit => "preattack_bonus_damage_post_crit",
            StatKey::BaseAttackBonusDamage => "baseattack_bonus_damage",
            StatKey::ProcattackBonusDamagePhysical => "procattack_bonus_damage_physical",
            StatKey::ProcattackBonusDamageMagical => "procattack_bonus_damage_magical",
            StatKey::ProcattackBonusDamagePure => "procattack_bonus_damage_pure",
            StatKey::ProcattackFeedback => "procattack_feedback",
            StatKey::InvisibilityLevel => "invisibility_level",
            StatKey::PersistentInvisibility => "persistent_invisibility",
            StatKey::AttackSpeedBaseOverride => "attackspeed_base_override",
            StatKey::FixedAttackRate => "fixed_attack_rate",
            StatKey::AttackSpeedBonusConstant => "attackspeed_bonus_constant",
            StatKey::CooldownReductionConstant => "cooldown_reduction_constant",
            StatKey::BaseAttackTimeConstant => "base_attack_time_constant",
            StatKey::AttackPointConstant => "attack_point_constant",
            StatKey::DamageOutgoingPercentage => "damageoutgoing_percentage",
            StatKey::TotalDamageOutgoingPercentage => "totaldamageoutgoing_percentage",
            StatKey::SpellAmplifyPercentage => "spell_amplify_percentage",
            StatKey::HpRegenAmplifyPercentage => "hp_regen_amplify_percentage",
            StatKey::MagicDamageOutgoingPercentage => "magicdamageoutgoing_percentage",
            StatKey::BaseDamageOutgoingPercentage => "basedamageoutgoing_percentage",
            StatKey::BaseDamageOutgoingPercentageUnique => "basedamageoutgoing_percentage_unique",
            StatKey::IncomingDamagePercentage => "incoming_damage_percentage",
            StatKey::IncomingPhysicalDamagePercentage => "incoming_physical_damage_percentage",
            StatKey::IncomingPhysicalDamageConstant => "incoming_physical_damage_constant",
            StatKey::IncomingSpellDamageConstant => "incoming_spell_damage_constant",
            StatKey::EvasionConstant => "evasion_constant",
            StatKey::NegativeEvasionConstant => "negative_evasion_constant",
            StatKey::AvoidDamage => "avoid_damage",
            StatKey::AvoidSpell => "avoid_spell",
            StatKey::MissPercentage => "miss_percentage",
            StatKey::PhysicalArmorBonus => "physical_armor_bonus",
            StatKey::PhysicalArmorBonusUnique => "physical_armor_bonus_unique",
            StatKey::PhysicalArmorBonusUniqueActive => "physical_armor_bonus_unique_active",
            StatKey::IgnorePhysicalArmor => "ignore_physical_armor",
            StatKey::MagicalResistanceDirectModification => "magical_resistance_direct_modification",
            StatKey::MagicalResistanceBonus => "magical_resistance_bonus",
            StatKey::MagicalResistanceDecrepifyUnique => "magical_resistance_decrepify_unique",
            StatKey::BaseManaRegen => "base_mana_regen",
            StatKey::ManaRegenConstant => "mana_regen_constant",
            StatKey::ManaRegenConstantUnique => "mana_regen_constant_unique",
            StatKey::ManaRegenPercentage => "mana_regen_percentage",
            StatKey::ManaRegenTotalPercentage => "mana_regen_total_percentage",
            StatKey::HealthRegenConstant => "health_regen_constant",
            StatKey::HealthRegenPercentage => "health_regen_percentage",
            StatKey::HealthBonus => "health_bonus",
            StatKey::ManaBonus => "mana_bonus",
            StatKey::ExtraStrengthBonus => "extra_strength_bonus",
            StatKey::ExtraHealthBonus => "extra_health_bonus",
            StatKey::ExtraManaBonus => "extra_mana_bonus",
            StatKey::ExtraHealthPercentage => "extra_health_percentage",
            StatKey::StatsStrengthBonus => "stats_strength_bonus",
            StatKey::StatsAgilityBonus => "stats_agility_bonus",
            StatKey::StatsIntellectBonus => "stats_intellect_bonus",
            StatKey::CastRangeBonus => "cast_range_bonus",
            StatKey::CastRangeBonusStacking => "cast_range_bonus_stacking",
            StatKey::AttackRangeBonus => "attack_range_bonus",
            StatKey::AttackRangeBonusUnique => "attack_range_bonus_unique",
            StatKey::MaxAttackRange => "max_attack_range",
            StatKey::ProjectileSpeedBonus => "projectile_speed_bonus",
            StatKey::CooldownPercentage => "cooldown_percentage",
            StatKey::CooldownPercentageStacking => "cooldown_percentage_stacking",
            StatKey::CastTimePercentage => "casttime_percentage",
            StatKey::ManaCostPercentage => "manacost_percentage",
            StatKey::PreattackCriticalStrike => "preattack_criticalstrike",
            StatKey::PreattackTargetCriticalStrike => "preattack_target_criticalstrike",
            StatKey::CritMultiplier => "crit_multiplier",
            StatKey::MagicalConstantBlock => "magical_constant_block",
            StatKey::PhysicalConstantBlock => "physical_constant_block",
            StatKey::PhysicalConstantBlockSpecial => "physical_constant_block_special",
            StatKey::TotalConstantBlockUnavoidablePreArmor => "total_constant_block_unavoidable_pre_armor",
            StatKey::TotalConstantBlock => "total_constant_block",
            StatKey::AbsorbSpell => "absorb_spell",
            StatKey::ReflectSpell => "reflect_spell",
            StatKey::DisableAutoattack => "disable_autoattack",
            StatKey::MinHealth => "min_health",
            StatKey::AbsoluteNoDamagePhysical => "absolute_no_damage_physical",
            StatKey::AbsoluteNoDamageMagical => "absolute_no_damage_magical",
            StatKey::AbsoluteNoDamagePure => "absolute_no_damage_pure",
            StatKey::DisableHealing => "disable_healing",
            StatKey::AlwaysAllowAttack => "always_allow_attack",
            StatKey::OverrideAttackMagical => "override_attack_magical",
            StatKey::Lifesteal => "lifesteal",
            StatKey::HealReceivedMultiplier => "heal_received_multiplier",
            StatKey::UnitStatsNeedsRefresh => "unit_stats_needs_refresh",
            StatKey::AccuracyBonus => "accuracy_bonus",
            StatKey::SplashBonus => "splash_bonus",
            StatKey::CritBonus => "crit_bonus",
            StatKey::SlowFactorOverride => "slow_factor_override",
            StatKey::SlowDurationBonus => "slow_duration_bonus",
            StatKey::AttackSpeedMultiplier => "attack_speed_multiplier",
            StatKey::MoveSpeedBonusConstant => "movespeed_bonus_constant",
            StatKey::MoveSpeedBaseOverride => "movespeed_base_override",
            StatKey::MoveSpeedBonusPercentage => "movespeed_bonus_percentage",
            StatKey::MoveSpeedBonusPercentageUnique => "movespeed_bonus_percentage_unique",
            StatKey::MoveSpeedBonusPercentageUnique2 => "movespeed_bonus_percentage_unique_2",
            StatKey::MoveSpeedBonusUnique => "movespeed_bonus_unique",
            StatKey::MoveSpeedBonusUnique2 => "movespeed_bonus_unique_2",
            StatKey::MoveSpeedAbsolute => "movespeed_absolute",
            StatKey::MoveSpeedAbsoluteMin => "movespeed_absolute_min",
            StatKey::MoveSpeedLimit => "movespeed_limit",
            StatKey::MoveSpeedMax => "movespeed_max",
            StatKey::TurnRatePercentage => "turn_rate_percentage",
            StatKey::Reincarnation => "reincarnation",
            StatKey::RespawnTime => "respawntime",
            StatKey::RespawnTimePercentage => "respawntime_percentage",
            StatKey::RespawnTimeStacking => "respawntime_stacking",
            StatKey::DeathGoldCost => "deathgoldcost",
            StatKey::ExpRateBoost => "exp_rate_boost",
            StatKey::BonusDayVision => "bonus_day_vision",
            StatKey::BonusNightVision => "bonus_night_vision",
            StatKey::BonusNightVisionUnique => "bonus_night_vision_unique",
            StatKey::BonusVisionPercentage => "bonus_vision_percentage",
            StatKey::FixedDayVision => "fixed_day_vision",
            StatKey::FixedNightVision => "fixed_night_vision",
            StatKey::IsIllusion => "is_illusion",
            StatKey::IllusionLabel => "illusion_label",
            StatKey::SuperIllusion => "super_illusion",
            StatKey::SuperIllusionWithUltimate => "super_illusion_with_ultimate",
            StatKey::DamageOutgoingPercentageIllusion => "damageoutgoing_percentage_illusion",
            StatKey::BountyCreepMultiplier => "bounty_creep_multiplier",
            StatKey::BountyOtherMultiplier => "bounty_other_multiplier",
            StatKey::PreAttack => "pre_attack",
            StatKey::OverrideAnimation => "override_animation",
            StatKey::OverrideAnimationWeight => "override_animation_weight",
            StatKey::OverrideAnimationRate => "override_animation_rate",
            StatKey::DisableTurning => "disable_turning",
            StatKey::IgnoreCastAngle => "ignore_cast_angle",
            StatKey::StunChance => "stun_chance",
            StatKey::StunDuration => "stun_duration",
            StatKey::CritChance => "crit_chance",
            StatKey::AttackStunChance => "attack_stun_chance",
            StatKey::AttackStunDuration => "attack_stun_duration",
        }
    }

    /// 將 wire-format 字串解析回 `StatKey`，未知值回 `None`。
    pub fn from_str_key(s: &str) -> Option<StatKey> {
        match s {
            "preattack_bonus_damage" => Some(StatKey::PreattackBonusDamage),
            "preattack_bonus_damage_proc" => Some(StatKey::PreattackBonusDamageProc),
            "preattack_bonus_damage_post_crit" => Some(StatKey::PreattackBonusDamagePostCrit),
            "baseattack_bonus_damage" => Some(StatKey::BaseAttackBonusDamage),
            "procattack_bonus_damage_physical" => Some(StatKey::ProcattackBonusDamagePhysical),
            "procattack_bonus_damage_magical" => Some(StatKey::ProcattackBonusDamageMagical),
            "procattack_bonus_damage_pure" => Some(StatKey::ProcattackBonusDamagePure),
            "procattack_feedback" => Some(StatKey::ProcattackFeedback),
            "invisibility_level" => Some(StatKey::InvisibilityLevel),
            "persistent_invisibility" => Some(StatKey::PersistentInvisibility),
            "attackspeed_base_override" => Some(StatKey::AttackSpeedBaseOverride),
            "fixed_attack_rate" => Some(StatKey::FixedAttackRate),
            "attackspeed_bonus_constant" => Some(StatKey::AttackSpeedBonusConstant),
            "cooldown_reduction_constant" => Some(StatKey::CooldownReductionConstant),
            "base_attack_time_constant" => Some(StatKey::BaseAttackTimeConstant),
            "attack_point_constant" => Some(StatKey::AttackPointConstant),
            "damageoutgoing_percentage" => Some(StatKey::DamageOutgoingPercentage),
            "totaldamageoutgoing_percentage" => Some(StatKey::TotalDamageOutgoingPercentage),
            "spell_amplify_percentage" => Some(StatKey::SpellAmplifyPercentage),
            "hp_regen_amplify_percentage" => Some(StatKey::HpRegenAmplifyPercentage),
            "magicdamageoutgoing_percentage" => Some(StatKey::MagicDamageOutgoingPercentage),
            "basedamageoutgoing_percentage" => Some(StatKey::BaseDamageOutgoingPercentage),
            "basedamageoutgoing_percentage_unique" => Some(StatKey::BaseDamageOutgoingPercentageUnique),
            "incoming_damage_percentage" => Some(StatKey::IncomingDamagePercentage),
            "incoming_physical_damage_percentage" => Some(StatKey::IncomingPhysicalDamagePercentage),
            "incoming_physical_damage_constant" => Some(StatKey::IncomingPhysicalDamageConstant),
            "incoming_spell_damage_constant" => Some(StatKey::IncomingSpellDamageConstant),
            "evasion_constant" => Some(StatKey::EvasionConstant),
            "negative_evasion_constant" => Some(StatKey::NegativeEvasionConstant),
            "avoid_damage" => Some(StatKey::AvoidDamage),
            "avoid_spell" => Some(StatKey::AvoidSpell),
            "miss_percentage" => Some(StatKey::MissPercentage),
            "physical_armor_bonus" => Some(StatKey::PhysicalArmorBonus),
            "physical_armor_bonus_unique" => Some(StatKey::PhysicalArmorBonusUnique),
            "physical_armor_bonus_unique_active" => Some(StatKey::PhysicalArmorBonusUniqueActive),
            "ignore_physical_armor" => Some(StatKey::IgnorePhysicalArmor),
            "magical_resistance_direct_modification" => Some(StatKey::MagicalResistanceDirectModification),
            "magical_resistance_bonus" => Some(StatKey::MagicalResistanceBonus),
            "magical_resistance_decrepify_unique" => Some(StatKey::MagicalResistanceDecrepifyUnique),
            "base_mana_regen" => Some(StatKey::BaseManaRegen),
            "mana_regen_constant" => Some(StatKey::ManaRegenConstant),
            "mana_regen_constant_unique" => Some(StatKey::ManaRegenConstantUnique),
            "mana_regen_percentage" => Some(StatKey::ManaRegenPercentage),
            "mana_regen_total_percentage" => Some(StatKey::ManaRegenTotalPercentage),
            "health_regen_constant" => Some(StatKey::HealthRegenConstant),
            "health_regen_percentage" => Some(StatKey::HealthRegenPercentage),
            "health_bonus" => Some(StatKey::HealthBonus),
            "mana_bonus" => Some(StatKey::ManaBonus),
            "extra_strength_bonus" => Some(StatKey::ExtraStrengthBonus),
            "extra_health_bonus" => Some(StatKey::ExtraHealthBonus),
            "extra_mana_bonus" => Some(StatKey::ExtraManaBonus),
            "extra_health_percentage" => Some(StatKey::ExtraHealthPercentage),
            "stats_strength_bonus" => Some(StatKey::StatsStrengthBonus),
            "stats_agility_bonus" => Some(StatKey::StatsAgilityBonus),
            "stats_intellect_bonus" => Some(StatKey::StatsIntellectBonus),
            "cast_range_bonus" => Some(StatKey::CastRangeBonus),
            "cast_range_bonus_stacking" => Some(StatKey::CastRangeBonusStacking),
            "attack_range_bonus" => Some(StatKey::AttackRangeBonus),
            "attack_range_bonus_unique" => Some(StatKey::AttackRangeBonusUnique),
            "max_attack_range" => Some(StatKey::MaxAttackRange),
            "projectile_speed_bonus" => Some(StatKey::ProjectileSpeedBonus),
            "cooldown_percentage" => Some(StatKey::CooldownPercentage),
            "cooldown_percentage_stacking" => Some(StatKey::CooldownPercentageStacking),
            "casttime_percentage" => Some(StatKey::CastTimePercentage),
            "manacost_percentage" => Some(StatKey::ManaCostPercentage),
            "preattack_criticalstrike" => Some(StatKey::PreattackCriticalStrike),
            "preattack_target_criticalstrike" => Some(StatKey::PreattackTargetCriticalStrike),
            "crit_multiplier" => Some(StatKey::CritMultiplier),
            "magical_constant_block" => Some(StatKey::MagicalConstantBlock),
            "physical_constant_block" => Some(StatKey::PhysicalConstantBlock),
            "physical_constant_block_special" => Some(StatKey::PhysicalConstantBlockSpecial),
            "total_constant_block_unavoidable_pre_armor" => Some(StatKey::TotalConstantBlockUnavoidablePreArmor),
            "total_constant_block" => Some(StatKey::TotalConstantBlock),
            "absorb_spell" => Some(StatKey::AbsorbSpell),
            "reflect_spell" => Some(StatKey::ReflectSpell),
            "disable_autoattack" => Some(StatKey::DisableAutoattack),
            "min_health" => Some(StatKey::MinHealth),
            "absolute_no_damage_physical" => Some(StatKey::AbsoluteNoDamagePhysical),
            "absolute_no_damage_magical" => Some(StatKey::AbsoluteNoDamageMagical),
            "absolute_no_damage_pure" => Some(StatKey::AbsoluteNoDamagePure),
            "disable_healing" => Some(StatKey::DisableHealing),
            "always_allow_attack" => Some(StatKey::AlwaysAllowAttack),
            "override_attack_magical" => Some(StatKey::OverrideAttackMagical),
            "lifesteal" => Some(StatKey::Lifesteal),
            "heal_received_multiplier" => Some(StatKey::HealReceivedMultiplier),
            "unit_stats_needs_refresh" => Some(StatKey::UnitStatsNeedsRefresh),
            "accuracy_bonus" => Some(StatKey::AccuracyBonus),
            "splash_bonus" => Some(StatKey::SplashBonus),
            "crit_bonus" => Some(StatKey::CritBonus),
            "slow_factor_override" => Some(StatKey::SlowFactorOverride),
            "slow_duration_bonus" => Some(StatKey::SlowDurationBonus),
            "attack_speed_multiplier" => Some(StatKey::AttackSpeedMultiplier),
            "movespeed_bonus_constant" => Some(StatKey::MoveSpeedBonusConstant),
            "movespeed_base_override" => Some(StatKey::MoveSpeedBaseOverride),
            "movespeed_bonus_percentage" => Some(StatKey::MoveSpeedBonusPercentage),
            "movespeed_bonus_percentage_unique" => Some(StatKey::MoveSpeedBonusPercentageUnique),
            "movespeed_bonus_percentage_unique_2" => Some(StatKey::MoveSpeedBonusPercentageUnique2),
            "movespeed_bonus_unique" => Some(StatKey::MoveSpeedBonusUnique),
            "movespeed_bonus_unique_2" => Some(StatKey::MoveSpeedBonusUnique2),
            "movespeed_absolute" => Some(StatKey::MoveSpeedAbsolute),
            "movespeed_absolute_min" => Some(StatKey::MoveSpeedAbsoluteMin),
            "movespeed_limit" => Some(StatKey::MoveSpeedLimit),
            "movespeed_max" => Some(StatKey::MoveSpeedMax),
            "turn_rate_percentage" => Some(StatKey::TurnRatePercentage),
            "reincarnation" => Some(StatKey::Reincarnation),
            "respawntime" => Some(StatKey::RespawnTime),
            "respawntime_percentage" => Some(StatKey::RespawnTimePercentage),
            "respawntime_stacking" => Some(StatKey::RespawnTimeStacking),
            "deathgoldcost" => Some(StatKey::DeathGoldCost),
            "exp_rate_boost" => Some(StatKey::ExpRateBoost),
            "bonus_day_vision" => Some(StatKey::BonusDayVision),
            "bonus_night_vision" => Some(StatKey::BonusNightVision),
            "bonus_night_vision_unique" => Some(StatKey::BonusNightVisionUnique),
            "bonus_vision_percentage" => Some(StatKey::BonusVisionPercentage),
            "fixed_day_vision" => Some(StatKey::FixedDayVision),
            "fixed_night_vision" => Some(StatKey::FixedNightVision),
            "is_illusion" => Some(StatKey::IsIllusion),
            "illusion_label" => Some(StatKey::IllusionLabel),
            "super_illusion" => Some(StatKey::SuperIllusion),
            "super_illusion_with_ultimate" => Some(StatKey::SuperIllusionWithUltimate),
            "damageoutgoing_percentage_illusion" => Some(StatKey::DamageOutgoingPercentageIllusion),
            "bounty_creep_multiplier" => Some(StatKey::BountyCreepMultiplier),
            "bounty_other_multiplier" => Some(StatKey::BountyOtherMultiplier),
            "pre_attack" => Some(StatKey::PreAttack),
            "override_animation" => Some(StatKey::OverrideAnimation),
            "override_animation_weight" => Some(StatKey::OverrideAnimationWeight),
            "override_animation_rate" => Some(StatKey::OverrideAnimationRate),
            "disable_turning" => Some(StatKey::DisableTurning),
            "ignore_cast_angle" => Some(StatKey::IgnoreCastAngle),
            "stun_chance" => Some(StatKey::StunChance),
            "stun_duration" => Some(StatKey::StunDuration),
            "crit_chance" => Some(StatKey::CritChance),
            "attack_stun_chance" => Some(StatKey::AttackStunChance),
            "attack_stun_duration" => Some(StatKey::AttackStunDuration),
            _ => None,
        }
    }

    /// 屬於哪個 `StatSection`（影響建築物 / 前端是否套用）。
    pub const fn section(self) -> StatSection {
        match self {
            StatKey::PreattackBonusDamage => StatSection::All,
            StatKey::PreattackBonusDamageProc => StatSection::All,
            StatKey::PreattackBonusDamagePostCrit => StatSection::All,
            StatKey::BaseAttackBonusDamage => StatSection::All,
            StatKey::ProcattackBonusDamagePhysical => StatSection::All,
            StatKey::ProcattackBonusDamageMagical => StatSection::All,
            StatKey::ProcattackBonusDamagePure => StatSection::All,
            StatKey::ProcattackFeedback => StatSection::All,
            StatKey::InvisibilityLevel => StatSection::All,
            StatKey::PersistentInvisibility => StatSection::All,
            StatKey::AttackSpeedBaseOverride => StatSection::All,
            StatKey::FixedAttackRate => StatSection::All,
            StatKey::AttackSpeedBonusConstant => StatSection::All,
            StatKey::CooldownReductionConstant => StatSection::All,
            StatKey::BaseAttackTimeConstant => StatSection::All,
            StatKey::AttackPointConstant => StatSection::All,
            StatKey::DamageOutgoingPercentage => StatSection::All,
            StatKey::TotalDamageOutgoingPercentage => StatSection::All,
            StatKey::SpellAmplifyPercentage => StatSection::All,
            StatKey::HpRegenAmplifyPercentage => StatSection::All,
            StatKey::MagicDamageOutgoingPercentage => StatSection::All,
            StatKey::BaseDamageOutgoingPercentage => StatSection::All,
            StatKey::BaseDamageOutgoingPercentageUnique => StatSection::All,
            StatKey::IncomingDamagePercentage => StatSection::All,
            StatKey::IncomingPhysicalDamagePercentage => StatSection::All,
            StatKey::IncomingPhysicalDamageConstant => StatSection::All,
            StatKey::IncomingSpellDamageConstant => StatSection::All,
            StatKey::EvasionConstant => StatSection::All,
            StatKey::NegativeEvasionConstant => StatSection::All,
            StatKey::AvoidDamage => StatSection::All,
            StatKey::AvoidSpell => StatSection::All,
            StatKey::MissPercentage => StatSection::All,
            StatKey::PhysicalArmorBonus => StatSection::All,
            StatKey::PhysicalArmorBonusUnique => StatSection::All,
            StatKey::PhysicalArmorBonusUniqueActive => StatSection::All,
            StatKey::IgnorePhysicalArmor => StatSection::All,
            StatKey::MagicalResistanceDirectModification => StatSection::All,
            StatKey::MagicalResistanceBonus => StatSection::All,
            StatKey::MagicalResistanceDecrepifyUnique => StatSection::All,
            StatKey::BaseManaRegen => StatSection::All,
            StatKey::ManaRegenConstant => StatSection::All,
            StatKey::ManaRegenConstantUnique => StatSection::All,
            StatKey::ManaRegenPercentage => StatSection::All,
            StatKey::ManaRegenTotalPercentage => StatSection::All,
            StatKey::HealthRegenConstant => StatSection::All,
            StatKey::HealthRegenPercentage => StatSection::All,
            StatKey::HealthBonus => StatSection::All,
            StatKey::ManaBonus => StatSection::All,
            StatKey::ExtraStrengthBonus => StatSection::All,
            StatKey::ExtraHealthBonus => StatSection::All,
            StatKey::ExtraManaBonus => StatSection::All,
            StatKey::ExtraHealthPercentage => StatSection::All,
            StatKey::StatsStrengthBonus => StatSection::All,
            StatKey::StatsAgilityBonus => StatSection::All,
            StatKey::StatsIntellectBonus => StatSection::All,
            StatKey::CastRangeBonus => StatSection::All,
            StatKey::CastRangeBonusStacking => StatSection::All,
            StatKey::AttackRangeBonus => StatSection::All,
            StatKey::AttackRangeBonusUnique => StatSection::All,
            StatKey::MaxAttackRange => StatSection::All,
            StatKey::ProjectileSpeedBonus => StatSection::All,
            StatKey::CooldownPercentage => StatSection::All,
            StatKey::CooldownPercentageStacking => StatSection::All,
            StatKey::CastTimePercentage => StatSection::All,
            StatKey::ManaCostPercentage => StatSection::All,
            StatKey::PreattackCriticalStrike => StatSection::All,
            StatKey::PreattackTargetCriticalStrike => StatSection::All,
            StatKey::CritMultiplier => StatSection::All,
            StatKey::MagicalConstantBlock => StatSection::All,
            StatKey::PhysicalConstantBlock => StatSection::All,
            StatKey::PhysicalConstantBlockSpecial => StatSection::All,
            StatKey::TotalConstantBlockUnavoidablePreArmor => StatSection::All,
            StatKey::TotalConstantBlock => StatSection::All,
            StatKey::AbsorbSpell => StatSection::All,
            StatKey::ReflectSpell => StatSection::All,
            StatKey::DisableAutoattack => StatSection::All,
            StatKey::MinHealth => StatSection::All,
            StatKey::AbsoluteNoDamagePhysical => StatSection::All,
            StatKey::AbsoluteNoDamageMagical => StatSection::All,
            StatKey::AbsoluteNoDamagePure => StatSection::All,
            StatKey::DisableHealing => StatSection::All,
            StatKey::AlwaysAllowAttack => StatSection::All,
            StatKey::OverrideAttackMagical => StatSection::All,
            StatKey::Lifesteal => StatSection::All,
            StatKey::HealReceivedMultiplier => StatSection::All,
            StatKey::UnitStatsNeedsRefresh => StatSection::All,
            StatKey::AccuracyBonus => StatSection::All,
            StatKey::SplashBonus => StatSection::All,
            StatKey::CritBonus => StatSection::All,
            StatKey::SlowFactorOverride => StatSection::All,
            StatKey::SlowDurationBonus => StatSection::All,
            StatKey::AttackSpeedMultiplier => StatSection::All,
            StatKey::MoveSpeedBonusConstant => StatSection::NonBuilding,
            StatKey::MoveSpeedBaseOverride => StatSection::NonBuilding,
            StatKey::MoveSpeedBonusPercentage => StatSection::NonBuilding,
            StatKey::MoveSpeedBonusPercentageUnique => StatSection::NonBuilding,
            StatKey::MoveSpeedBonusPercentageUnique2 => StatSection::NonBuilding,
            StatKey::MoveSpeedBonusUnique => StatSection::NonBuilding,
            StatKey::MoveSpeedBonusUnique2 => StatSection::NonBuilding,
            StatKey::MoveSpeedAbsolute => StatSection::NonBuilding,
            StatKey::MoveSpeedAbsoluteMin => StatSection::NonBuilding,
            StatKey::MoveSpeedLimit => StatSection::NonBuilding,
            StatKey::MoveSpeedMax => StatSection::NonBuilding,
            StatKey::TurnRatePercentage => StatSection::NonBuilding,
            StatKey::Reincarnation => StatSection::NonBuilding,
            StatKey::RespawnTime => StatSection::NonBuilding,
            StatKey::RespawnTimePercentage => StatSection::NonBuilding,
            StatKey::RespawnTimeStacking => StatSection::NonBuilding,
            StatKey::DeathGoldCost => StatSection::NonBuilding,
            StatKey::ExpRateBoost => StatSection::NonBuilding,
            StatKey::BonusDayVision => StatSection::NonBuilding,
            StatKey::BonusNightVision => StatSection::NonBuilding,
            StatKey::BonusNightVisionUnique => StatSection::NonBuilding,
            StatKey::BonusVisionPercentage => StatSection::NonBuilding,
            StatKey::FixedDayVision => StatSection::NonBuilding,
            StatKey::FixedNightVision => StatSection::NonBuilding,
            StatKey::IsIllusion => StatSection::NonBuilding,
            StatKey::IllusionLabel => StatSection::NonBuilding,
            StatKey::SuperIllusion => StatSection::NonBuilding,
            StatKey::SuperIllusionWithUltimate => StatSection::NonBuilding,
            StatKey::DamageOutgoingPercentageIllusion => StatSection::NonBuilding,
            StatKey::BountyCreepMultiplier => StatSection::NonBuilding,
            StatKey::BountyOtherMultiplier => StatSection::NonBuilding,
            StatKey::PreAttack => StatSection::Visual,
            StatKey::OverrideAnimation => StatSection::Visual,
            StatKey::OverrideAnimationWeight => StatSection::Visual,
            StatKey::OverrideAnimationRate => StatSection::Visual,
            StatKey::DisableTurning => StatSection::Visual,
            StatKey::IgnoreCastAngle => StatSection::Visual,
            StatKey::StunChance => StatSection::Visual,
            StatKey::StunDuration => StatSection::Visual,
            StatKey::CritChance => StatSection::All,
            StatKey::AttackStunChance => StatSection::All,
            StatKey::AttackStunDuration => StatSection::All,
        }
    }

    /// 對應的 BuffStore 聚合規則。
    pub const fn aggregation(self) -> Aggregation {
        match self {
            StatKey::PreattackBonusDamage => Aggregation::SumAdd,
            StatKey::PreattackBonusDamageProc => Aggregation::SumAdd,
            StatKey::PreattackBonusDamagePostCrit => Aggregation::SumAdd,
            StatKey::BaseAttackBonusDamage => Aggregation::SumAdd,
            StatKey::ProcattackBonusDamagePhysical => Aggregation::SumAdd,
            StatKey::ProcattackBonusDamageMagical => Aggregation::SumAdd,
            StatKey::ProcattackBonusDamagePure => Aggregation::SumAdd,
            StatKey::ProcattackFeedback => Aggregation::SumAdd,
            StatKey::InvisibilityLevel => Aggregation::PassThrough,
            StatKey::PersistentInvisibility => Aggregation::PassThrough,
            StatKey::AttackSpeedBaseOverride => Aggregation::PassThrough,
            StatKey::FixedAttackRate => Aggregation::PassThrough,
            StatKey::AttackSpeedBonusConstant => Aggregation::SumAdd,
            StatKey::CooldownReductionConstant => Aggregation::SumAdd,
            StatKey::BaseAttackTimeConstant => Aggregation::SumAdd,
            StatKey::AttackPointConstant => Aggregation::SumAdd,
            StatKey::DamageOutgoingPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::TotalDamageOutgoingPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::SpellAmplifyPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::HpRegenAmplifyPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::MagicDamageOutgoingPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::BaseDamageOutgoingPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::BaseDamageOutgoingPercentageUnique => Aggregation::SumAddThenMul1Plus,
            StatKey::IncomingDamagePercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::IncomingPhysicalDamagePercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::IncomingPhysicalDamageConstant => Aggregation::SumAdd,
            StatKey::IncomingSpellDamageConstant => Aggregation::SumAdd,
            StatKey::EvasionConstant => Aggregation::SumAdd,
            StatKey::NegativeEvasionConstant => Aggregation::SumAdd,
            StatKey::AvoidDamage => Aggregation::PassThrough,
            StatKey::AvoidSpell => Aggregation::PassThrough,
            StatKey::MissPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::PhysicalArmorBonus => Aggregation::SumAdd,
            StatKey::PhysicalArmorBonusUnique => Aggregation::SumAdd,
            StatKey::PhysicalArmorBonusUniqueActive => Aggregation::SumAdd,
            StatKey::IgnorePhysicalArmor => Aggregation::PassThrough,
            StatKey::MagicalResistanceDirectModification => Aggregation::PassThrough,
            StatKey::MagicalResistanceBonus => Aggregation::SumAdd,
            StatKey::MagicalResistanceDecrepifyUnique => Aggregation::PassThrough,
            StatKey::BaseManaRegen => Aggregation::PassThrough,
            StatKey::ManaRegenConstant => Aggregation::SumAdd,
            StatKey::ManaRegenConstantUnique => Aggregation::SumAdd,
            StatKey::ManaRegenPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::ManaRegenTotalPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::HealthRegenConstant => Aggregation::SumAdd,
            StatKey::HealthRegenPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::HealthBonus => Aggregation::SumAdd,
            StatKey::ManaBonus => Aggregation::SumAdd,
            StatKey::ExtraStrengthBonus => Aggregation::SumAdd,
            StatKey::ExtraHealthBonus => Aggregation::SumAdd,
            StatKey::ExtraManaBonus => Aggregation::SumAdd,
            StatKey::ExtraHealthPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::StatsStrengthBonus => Aggregation::SumAdd,
            StatKey::StatsAgilityBonus => Aggregation::SumAdd,
            StatKey::StatsIntellectBonus => Aggregation::SumAdd,
            StatKey::CastRangeBonus => Aggregation::SumAdd,
            StatKey::CastRangeBonusStacking => Aggregation::SumAdd,
            StatKey::AttackRangeBonus => Aggregation::SumAdd,
            StatKey::AttackRangeBonusUnique => Aggregation::SumAdd,
            StatKey::MaxAttackRange => Aggregation::PassThrough,
            StatKey::ProjectileSpeedBonus => Aggregation::SumAdd,
            StatKey::CooldownPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::CooldownPercentageStacking => Aggregation::SumAddThenMul1Plus,
            StatKey::CastTimePercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::ManaCostPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::PreattackCriticalStrike => Aggregation::PassThrough,
            StatKey::PreattackTargetCriticalStrike => Aggregation::PassThrough,
            StatKey::CritMultiplier => Aggregation::ProductMult,
            StatKey::MagicalConstantBlock => Aggregation::SumAdd,
            StatKey::PhysicalConstantBlock => Aggregation::SumAdd,
            StatKey::PhysicalConstantBlockSpecial => Aggregation::SumAdd,
            StatKey::TotalConstantBlockUnavoidablePreArmor => Aggregation::SumAdd,
            StatKey::TotalConstantBlock => Aggregation::SumAdd,
            StatKey::AbsorbSpell => Aggregation::PassThrough,
            StatKey::ReflectSpell => Aggregation::PassThrough,
            StatKey::DisableAutoattack => Aggregation::PassThrough,
            StatKey::MinHealth => Aggregation::PassThrough,
            StatKey::AbsoluteNoDamagePhysical => Aggregation::SumAdd,
            StatKey::AbsoluteNoDamageMagical => Aggregation::SumAdd,
            StatKey::AbsoluteNoDamagePure => Aggregation::SumAdd,
            StatKey::DisableHealing => Aggregation::PassThrough,
            StatKey::AlwaysAllowAttack => Aggregation::PassThrough,
            StatKey::OverrideAttackMagical => Aggregation::PassThrough,
            StatKey::Lifesteal => Aggregation::PassThrough,
            StatKey::HealReceivedMultiplier => Aggregation::ProductMult,
            StatKey::UnitStatsNeedsRefresh => Aggregation::PassThrough,
            StatKey::AccuracyBonus => Aggregation::SumAdd,
            StatKey::SplashBonus => Aggregation::SumAdd,
            StatKey::CritBonus => Aggregation::SumAdd,
            StatKey::SlowFactorOverride => Aggregation::PassThrough,
            StatKey::SlowDurationBonus => Aggregation::SumAdd,
            StatKey::AttackSpeedMultiplier => Aggregation::ProductMult,
            StatKey::MoveSpeedBonusConstant => Aggregation::SumAdd,
            StatKey::MoveSpeedBaseOverride => Aggregation::PassThrough,
            StatKey::MoveSpeedBonusPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::MoveSpeedBonusPercentageUnique => Aggregation::SumAddThenMul1Plus,
            StatKey::MoveSpeedBonusPercentageUnique2 => Aggregation::SumAddThenMul1Plus,
            StatKey::MoveSpeedBonusUnique => Aggregation::SumAdd,
            StatKey::MoveSpeedBonusUnique2 => Aggregation::SumAdd,
            StatKey::MoveSpeedAbsolute => Aggregation::SumAdd,
            StatKey::MoveSpeedAbsoluteMin => Aggregation::SumAdd,
            StatKey::MoveSpeedLimit => Aggregation::PassThrough,
            StatKey::MoveSpeedMax => Aggregation::PassThrough,
            StatKey::TurnRatePercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::Reincarnation => Aggregation::PassThrough,
            StatKey::RespawnTime => Aggregation::PassThrough,
            StatKey::RespawnTimePercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::RespawnTimeStacking => Aggregation::SumAdd,
            StatKey::DeathGoldCost => Aggregation::PassThrough,
            StatKey::ExpRateBoost => Aggregation::PassThrough,
            StatKey::BonusDayVision => Aggregation::SumAdd,
            StatKey::BonusNightVision => Aggregation::SumAdd,
            StatKey::BonusNightVisionUnique => Aggregation::SumAdd,
            StatKey::BonusVisionPercentage => Aggregation::SumAddThenMul1Plus,
            StatKey::FixedDayVision => Aggregation::PassThrough,
            StatKey::FixedNightVision => Aggregation::PassThrough,
            StatKey::IsIllusion => Aggregation::PassThrough,
            StatKey::IllusionLabel => Aggregation::PassThrough,
            StatKey::SuperIllusion => Aggregation::PassThrough,
            StatKey::SuperIllusionWithUltimate => Aggregation::PassThrough,
            StatKey::DamageOutgoingPercentageIllusion => Aggregation::SumAddThenMul1Plus,
            StatKey::BountyCreepMultiplier => Aggregation::ProductMult,
            StatKey::BountyOtherMultiplier => Aggregation::ProductMult,
            StatKey::PreAttack => Aggregation::PassThrough,
            StatKey::OverrideAnimation => Aggregation::PassThrough,
            StatKey::OverrideAnimationWeight => Aggregation::PassThrough,
            StatKey::OverrideAnimationRate => Aggregation::PassThrough,
            StatKey::DisableTurning => Aggregation::PassThrough,
            StatKey::IgnoreCastAngle => Aggregation::PassThrough,
            StatKey::StunChance => Aggregation::Chance,
            StatKey::StunDuration => Aggregation::PassThrough,
            StatKey::CritChance => Aggregation::Chance,
            StatKey::AttackStunChance => Aggregation::Chance,
            StatKey::AttackStunDuration => Aggregation::SumAdd,
        }
    }
}

/// 按 discriminant 排序的所有 `StatKey` variant — 供 gen-docs / 遍歷測試使用。
pub const ALL: &[StatKey; 134] = &[
    StatKey::PreattackBonusDamage,
    StatKey::PreattackBonusDamageProc,
    StatKey::PreattackBonusDamagePostCrit,
    StatKey::BaseAttackBonusDamage,
    StatKey::ProcattackBonusDamagePhysical,
    StatKey::ProcattackBonusDamageMagical,
    StatKey::ProcattackBonusDamagePure,
    StatKey::ProcattackFeedback,
    StatKey::InvisibilityLevel,
    StatKey::PersistentInvisibility,
    StatKey::AttackSpeedBaseOverride,
    StatKey::FixedAttackRate,
    StatKey::AttackSpeedBonusConstant,
    StatKey::CooldownReductionConstant,
    StatKey::BaseAttackTimeConstant,
    StatKey::AttackPointConstant,
    StatKey::DamageOutgoingPercentage,
    StatKey::TotalDamageOutgoingPercentage,
    StatKey::SpellAmplifyPercentage,
    StatKey::HpRegenAmplifyPercentage,
    StatKey::MagicDamageOutgoingPercentage,
    StatKey::BaseDamageOutgoingPercentage,
    StatKey::BaseDamageOutgoingPercentageUnique,
    StatKey::IncomingDamagePercentage,
    StatKey::IncomingPhysicalDamagePercentage,
    StatKey::IncomingPhysicalDamageConstant,
    StatKey::IncomingSpellDamageConstant,
    StatKey::EvasionConstant,
    StatKey::NegativeEvasionConstant,
    StatKey::AvoidDamage,
    StatKey::AvoidSpell,
    StatKey::MissPercentage,
    StatKey::PhysicalArmorBonus,
    StatKey::PhysicalArmorBonusUnique,
    StatKey::PhysicalArmorBonusUniqueActive,
    StatKey::IgnorePhysicalArmor,
    StatKey::MagicalResistanceDirectModification,
    StatKey::MagicalResistanceBonus,
    StatKey::MagicalResistanceDecrepifyUnique,
    StatKey::BaseManaRegen,
    StatKey::ManaRegenConstant,
    StatKey::ManaRegenConstantUnique,
    StatKey::ManaRegenPercentage,
    StatKey::ManaRegenTotalPercentage,
    StatKey::HealthRegenConstant,
    StatKey::HealthRegenPercentage,
    StatKey::HealthBonus,
    StatKey::ManaBonus,
    StatKey::ExtraStrengthBonus,
    StatKey::ExtraHealthBonus,
    StatKey::ExtraManaBonus,
    StatKey::ExtraHealthPercentage,
    StatKey::StatsStrengthBonus,
    StatKey::StatsAgilityBonus,
    StatKey::StatsIntellectBonus,
    StatKey::CastRangeBonus,
    StatKey::CastRangeBonusStacking,
    StatKey::AttackRangeBonus,
    StatKey::AttackRangeBonusUnique,
    StatKey::MaxAttackRange,
    StatKey::ProjectileSpeedBonus,
    StatKey::CooldownPercentage,
    StatKey::CooldownPercentageStacking,
    StatKey::CastTimePercentage,
    StatKey::ManaCostPercentage,
    StatKey::PreattackCriticalStrike,
    StatKey::PreattackTargetCriticalStrike,
    StatKey::CritMultiplier,
    StatKey::MagicalConstantBlock,
    StatKey::PhysicalConstantBlock,
    StatKey::PhysicalConstantBlockSpecial,
    StatKey::TotalConstantBlockUnavoidablePreArmor,
    StatKey::TotalConstantBlock,
    StatKey::AbsorbSpell,
    StatKey::ReflectSpell,
    StatKey::DisableAutoattack,
    StatKey::MinHealth,
    StatKey::AbsoluteNoDamagePhysical,
    StatKey::AbsoluteNoDamageMagical,
    StatKey::AbsoluteNoDamagePure,
    StatKey::DisableHealing,
    StatKey::AlwaysAllowAttack,
    StatKey::OverrideAttackMagical,
    StatKey::Lifesteal,
    StatKey::HealReceivedMultiplier,
    StatKey::UnitStatsNeedsRefresh,
    StatKey::AccuracyBonus,
    StatKey::SplashBonus,
    StatKey::CritBonus,
    StatKey::SlowFactorOverride,
    StatKey::SlowDurationBonus,
    StatKey::AttackSpeedMultiplier,
    StatKey::MoveSpeedBonusConstant,
    StatKey::MoveSpeedBaseOverride,
    StatKey::MoveSpeedBonusPercentage,
    StatKey::MoveSpeedBonusPercentageUnique,
    StatKey::MoveSpeedBonusPercentageUnique2,
    StatKey::MoveSpeedBonusUnique,
    StatKey::MoveSpeedBonusUnique2,
    StatKey::MoveSpeedAbsolute,
    StatKey::MoveSpeedAbsoluteMin,
    StatKey::MoveSpeedLimit,
    StatKey::MoveSpeedMax,
    StatKey::TurnRatePercentage,
    StatKey::Reincarnation,
    StatKey::RespawnTime,
    StatKey::RespawnTimePercentage,
    StatKey::RespawnTimeStacking,
    StatKey::DeathGoldCost,
    StatKey::ExpRateBoost,
    StatKey::BonusDayVision,
    StatKey::BonusNightVision,
    StatKey::BonusNightVisionUnique,
    StatKey::BonusVisionPercentage,
    StatKey::FixedDayVision,
    StatKey::FixedNightVision,
    StatKey::IsIllusion,
    StatKey::IllusionLabel,
    StatKey::SuperIllusion,
    StatKey::SuperIllusionWithUltimate,
    StatKey::DamageOutgoingPercentageIllusion,
    StatKey::BountyCreepMultiplier,
    StatKey::BountyOtherMultiplier,
    StatKey::PreAttack,
    StatKey::OverrideAnimation,
    StatKey::OverrideAnimationWeight,
    StatKey::OverrideAnimationRate,
    StatKey::DisableTurning,
    StatKey::IgnoreCastAngle,
    StatKey::StunChance,
    StatKey::StunDuration,
    StatKey::CritChance,
    StatKey::AttackStunChance,
    StatKey::AttackStunDuration,
];

// ============================================================
// Buff IDs
// ============================================================
// 以下是 buff identifier 字串常數（供 GameWorld::add_buff /
// remove_buff / has_buff 等 API 使用），不是 stat property key，
// 不納入 StatKey enum。

pub const BUFF_ID_STUN: &str = "stun";
pub const BUFF_ID_ROOT: &str = "root";
pub const BUFF_ID_SILENCE: &str = "silence";
pub const BUFF_ID_INVISIBLE: &str = "invisible";
pub const BUFF_ID_INVULNERABLE: &str = "invulnerable";

#[cfg(test)]
mod tests {
    use super::{StatKey, StatSection, Aggregation, ALL};

    #[test]
    fn all_array_length_is_134() {
        assert_eq!(ALL.len(), 134);
    }

    #[test]
    fn as_str_to_from_str_roundtrip_all() {
        for &k in ALL {
            assert_eq!(
                StatKey::from_str_key(k.as_str()),
                Some(k),
                "round-trip failed for {:?}",
                k
            );
        }
    }

    #[test]
    fn from_str_unknown_returns_none() {
        assert_eq!(StatKey::from_str_key("not_a_real_key"), None);
    }

    #[test]
    fn discriminants_are_sequential() {
        for (i, &k) in ALL.iter().enumerate() {
            assert_eq!(k as u16, i as u16, "discriminant mismatch at {}", i);
        }
    }

    #[test]
    fn section_and_aggregation_spot_checks() {
        // SECTION 1 通用 + _bonus → SumAdd
        assert_eq!(StatKey::PreattackBonusDamage.section(), StatSection::All);
        assert_eq!(
            StatKey::PreattackBonusDamage.aggregation(),
            Aggregation::SumAdd
        );
        // SECTION 2 NonBuilding + _percentage → SumAddThenMul1Plus
        assert_eq!(
            StatKey::MoveSpeedBonusPercentage.section(),
            StatSection::NonBuilding
        );
        assert_eq!(
            StatKey::MoveSpeedBonusPercentage.aggregation(),
            Aggregation::SumAddThenMul1Plus
        );
        // SECTION 3 Visual
        assert_eq!(StatKey::PreAttack.section(), StatSection::Visual);
        // _multiplier → ProductMult
        assert_eq!(
            StatKey::AttackSpeedMultiplier.aggregation(),
            Aggregation::ProductMult
        );
        // _chance → Chance
        assert_eq!(
            StatKey::CritChance.aggregation(),
            Aggregation::Chance
        );
    }

    #[test]
    fn new_tower_variants_exist() {
        // 7 個新 variant 都可以 round-trip
        let new_keys = [
            StatKey::CritChance,
            StatKey::CritBonus,
            StatKey::SplashBonus,
            StatKey::SlowFactorOverride,
            StatKey::SlowDurationBonus,
            StatKey::AttackStunChance,
            StatKey::AttackStunDuration,
        ];
        for k in new_keys {
            assert_eq!(StatKey::from_str_key(k.as_str()), Some(k));
        }
    }
}
