//! Build-time codegen for template ids.
//!
//! Reads `omb/Story/templates.json` and emits `template_ids_gen.rs` into OUT_DIR.
//! Id allocation: sequential u16 in JSON declaration order, starting from 1.
//! Id 0 is reserved as UNSPECIFIED. Tombstone entries (`"tombstone": true`)
//! consume an id but emit no const / lookup entry — append-only safety.

use serde::Deserialize;
use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Manifest {
    #[serde(default)] towers: Vec<TowerEntry>,
    #[serde(default)] heroes: Vec<HeroEntry>,
    #[serde(default)] abilities: Vec<Entry>,
    #[serde(default)] buffs: Vec<Entry>,
    #[serde(default)] summons: Vec<Entry>,
    #[serde(default)] creeps: Vec<Entry>,
    #[serde(default)] projectile_kinds: Vec<ProjKind>,
}

#[derive(Deserialize, Clone)]
struct Entry {
    id: String,
    #[serde(default)] display_name: String,
    #[serde(default)] tombstone: bool,
}

/// Tower entry — id + display_name + 全部 stat 欄位都從 templates.json 讀。
/// 對應 omoba_template_ids::TowerStats（src/lib.rs）— 增欄位時兩邊都要改。
#[derive(Deserialize, Clone)]
struct TowerEntry {
    id: String,
    #[serde(default)] display_name: String,
    #[serde(default)] tombstone: bool,
    #[serde(default)] atk: f32,
    #[serde(default)] asd_interval: f32,
    #[serde(default)] range: f32,
    #[serde(default)] bullet_speed: f32,
    #[serde(default)] splash_radius: f32,
    #[serde(default)] hit_radius: f32,
    #[serde(default)] slow_factor: f32,
    #[serde(default)] slow_duration: f32,
    #[serde(default)] cost: i32,
    #[serde(default)] footprint: f32,
    #[serde(default)] hp: f32,
    #[serde(default)] turn_speed_deg: f32,
}

#[derive(Deserialize)]
struct HeroEntry {
    id: String,
    #[serde(default)] display_name: String,
    #[serde(default)] title: String,
    #[serde(default)] tombstone: bool,
    #[serde(default)] abilities: Vec<String>,
}

#[derive(Deserialize)]
struct ProjKind {
    id: String,
    #[serde(default)] tombstone: bool,
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let json_path = manifest_dir.parent().unwrap().join("omb/Story/templates.json");
    println!("cargo:rerun-if-changed={}", json_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&json_path)
        .unwrap_or_else(|e| panic!("read {}: {}", json_path.display(), e));
    let m: Manifest = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("parse templates.json: {}", e));

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by omoba-template-ids/build.rs — DO NOT EDIT.\n");
    out.push_str("// Source: omb/Story/templates.json\n\n");

    emit_tower_namespace(&mut out, &m.towers);
    emit_hero_namespace(&mut out, &m.heroes);
    emit_namespace(&mut out, "Ability",        "ability",    &m.abilities, true);
    emit_namespace(&mut out, "Buff",           "buff",       &m.buffs,     true);
    emit_namespace(&mut out, "Summon",         "summon",     &m.summons,   true);
    emit_namespace(&mut out, "Creep",          "creep",      &m.creeps,    true);
    emit_projectile_kinds(&mut out, &m.projectile_kinds);

    // Hero → abilities lookup（必須在 abilities namespace emit 後做，因為 AbilityId 才存在）。
    // build.rs 自己 build 一個 ability id map，把字串 abilities 翻成 raw u16。
    let mut ability_id_map: std::collections::HashMap<&str, u16> =
        std::collections::HashMap::new();
    let mut next_aid: u16 = 1;
    for a in &m.abilities {
        if !a.tombstone {
            ability_id_map.insert(&a.id, next_aid);
        }
        next_aid += 1;
    }
    emit_hero_abilities(&mut out, &m.heroes, &ability_id_map);

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = format!("{}/template_ids_gen.rs", out_dir);
    fs::write(&out_path, out).unwrap();
}

fn escape_str_literal(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Strip a leading namespace prefix (e.g. "tower_tack" → "tack" when ns="tower").
/// Falls back to the full id when no prefix match.
fn strip_prefix<'a>(id: &'a str, ns_lower: &str) -> &'a str {
    let pfx = format!("{}_", ns_lower);
    id.strip_prefix(&pfx).unwrap_or(id)
}

/// Build the exported const identifier. For namespace "tower" and id "tower_tack",
/// returns "TOWER_TACK". If id already has the namespace prefix, it is removed.
fn const_name(ns_lower: &str, id: &str) -> String {
    let ns_upper = ns_lower.to_uppercase();
    let stripped = strip_prefix(id, ns_lower);
    // Guard: after stripping, "tack".to_uppercase() = "TACK" → ns_upper + "_" + "TACK"
    format!("{}_{}", ns_upper, stripped.to_uppercase())
}

fn emit_namespace(out: &mut String, ty: &str, ns_lower: &str, entries: &[Entry], has_display: bool) {
    // newtype with #[repr(transparent)] — wire-safe for abi_stable via raw u16
    // newtype with #[repr(transparent)] — wire-safe for abi_stable via raw u16.
    // `.as_str()` returns the original id string ("tower_tack" etc.) for use
    // where FFI still expects RStr<'_> — scripts do `RStr::from_str(TOWER_TACK.as_str())`
    // which is still compile-time-checked via const existence.
    out.push_str(&format!(
        "#[repr(transparent)]\n\
         #[derive(Copy, Clone, Eq, PartialEq, Hash, Debug, Default)]\n\
         pub struct {}Id(pub u16);\n\
         impl {}Id {{\n\
         \tpub const UNSPECIFIED: Self = Self(0);\n\
         \tpub const fn raw(self) -> u16 {{ self.0 }}\n\
         \tpub fn as_str(self) -> &'static str {{ {}_id_str(self) }}\n\
         }}\n\n",
        ty, ty, ns_lower,
    ));

    // consts — sequential 1..N skipping tombstones (but consuming id number)
    let mut seen: HashSet<&str> = HashSet::new();
    let mut next: u16 = 1;
    for e in entries {
        if !e.tombstone {
            if !seen.insert(&e.id) {
                panic!("duplicate {} id: {}", ty, e.id);
            }
            let cname = const_name(ns_lower, &e.id);
            out.push_str(&format!(
                "pub const {}: {}Id = {}Id({});\n",
                cname, ty, ty, next,
            ));
        }
        next = next.checked_add(1)
            .unwrap_or_else(|| panic!("{}Id exhausted u16 space", ty));
    }
    out.push('\n');

    // forward lookup: name → Option<Id>
    out.push_str(&format!(
        "pub fn {}_by_name(s: &str) -> Option<{}Id> {{\n\tmatch s {{\n",
        ns_lower, ty,
    ));
    let mut next: u16 = 1;
    for e in entries {
        if !e.tombstone {
            out.push_str(&format!(
                "\t\t\"{}\" => Some({}Id({})),\n",
                escape_str_literal(&e.id), ty, next,
            ));
        }
        next += 1;
    }
    out.push_str("\t\t_ => None,\n\t}\n}\n\n");

    // reverse: id → original id string (for logs / backward-compat JSON)
    out.push_str(&format!(
        "pub fn {}_id_str(id: {}Id) -> &'static str {{\n\tmatch id.0 {{\n\t\t0 => \"\",\n",
        ns_lower, ty,
    ));
    let mut next: u16 = 1;
    for e in entries {
        if !e.tombstone {
            out.push_str(&format!(
                "\t\t{} => \"{}\",\n",
                next, escape_str_literal(&e.id),
            ));
        }
        next += 1;
    }
    out.push_str(
        "\t\t_ => {\n\
         \t\t\tdebug_assert!(false, \"unknown id: {}\", id.0);\n\
         \t\t\t\"?\"\n\
         \t\t}\n\
         \t}\n}\n\n",
    );

    // display lookup if applicable
    if has_display {
        out.push_str(&format!(
            "pub fn {}_display(id: {}Id) -> &'static str {{\n\tmatch id.0 {{\n\t\t0 => \"\",\n",
            ns_lower, ty,
        ));
        let mut next: u16 = 1;
        for e in entries {
            if !e.tombstone {
                let display = if e.display_name.is_empty() { &e.id } else { &e.display_name };
                out.push_str(&format!(
                    "\t\t{} => \"{}\",\n",
                    next, escape_str_literal(display),
                ));
            }
            next += 1;
        }
        out.push_str(
            "\t\t_ => {\n\
             \t\t\tdebug_assert!(false, \"unknown id: {}\", id.0);\n\
             \t\t\t\"?\"\n\
             \t\t}\n\
             \t}\n}\n\n",
        );
    }
}

/// Towers 走自己的 emit：除了 id/display 外還要生 `TOWER_<NAME>_STATS: TowerStats`
/// 跟 `tower_stats(id)` lookup。
fn emit_tower_namespace(out: &mut String, entries: &[TowerEntry]) {
    let converted: Vec<Entry> = entries.iter().map(|t| Entry {
        id: t.id.clone(),
        display_name: t.display_name.clone(),
        tombstone: t.tombstone,
    }).collect();
    emit_namespace(out, "Tower", "tower", &converted, /*display*/true);

    // Per-tower const: TOWER_<NAME>_STATS
    for e in entries {
        if e.tombstone {
            continue;
        }
        let cname = const_name("tower", &e.id);
        out.push_str(&format!(
            "pub const {}_STATS: TowerStats = TowerStats {{\n\
             \tatk: {:?}_f32,\n\
             \tasd_interval: {:?}_f32,\n\
             \trange: {:?}_f32,\n\
             \tbullet_speed: {:?}_f32,\n\
             \tsplash_radius: {:?}_f32,\n\
             \thit_radius: {:?}_f32,\n\
             \tslow_factor: {:?}_f32,\n\
             \tslow_duration: {:?}_f32,\n\
             \tcost: {}i32,\n\
             \tfootprint: {:?}_f32,\n\
             \thp: {:?}_f32,\n\
             \tturn_speed_deg: {:?}_f32,\n\
             }};\n",
            cname,
            e.atk, e.asd_interval, e.range, e.bullet_speed,
            e.splash_radius, e.hit_radius, e.slow_factor, e.slow_duration,
            e.cost, e.footprint, e.hp, e.turn_speed_deg,
        ));
    }
    out.push('\n');

    // Lookup tower_stats(TowerId) → Option<&'static TowerStats>
    out.push_str("pub fn tower_stats(id: TowerId) -> Option<&'static TowerStats> {\n\tmatch id.0 {\n");
    let mut next: u16 = 1;
    for e in entries {
        if !e.tombstone {
            let cname = const_name("tower", &e.id);
            out.push_str(&format!(
                "\t\t{} => Some(&{}_STATS),\n",
                next, cname,
            ));
        }
        next += 1;
    }
    out.push_str("\t\t_ => None,\n\t}\n}\n\n");
}

fn emit_hero_namespace(out: &mut String, entries: &[HeroEntry]) {
    // Reuse emit_namespace machinery for id/display; add hero_title lookup.
    let converted: Vec<Entry> = entries.iter().map(|h| Entry {
        id: h.id.clone(),
        display_name: h.display_name.clone(),
        tombstone: h.tombstone,
    }).collect();
    emit_namespace(out, "Hero", "hero", &converted, true);

    out.push_str("pub fn hero_title(id: HeroId) -> &'static str {\n\tmatch id.0 {\n\t\t0 => \"\",\n");
    let mut next: u16 = 1;
    for h in entries {
        if !h.tombstone {
            out.push_str(&format!(
                "\t\t{} => \"{}\",\n",
                next, escape_str_literal(&h.title),
            ));
        }
        next += 1;
    }
    out.push_str("\t\t_ => \"\",\n\t}\n}\n\n");
}

/// Hero → abilities[] codegen — 從 templates.json heroes[i].abilities 字串陣列翻成
/// `HERO_<NAME>_ABILITIES: &[AbilityId] = &[AbilityId(N), ...]` const + lookup
/// `hero_abilities(HeroId) -> &'static [AbilityId]`。消除 omoba-core 端寫死的
/// `match hero_type { "saika_..." => [...] }` match 表。
fn emit_hero_abilities(
    out: &mut String,
    entries: &[HeroEntry],
    ability_ids: &std::collections::HashMap<&str, u16>,
) {
    for e in entries {
        if e.tombstone {
            continue;
        }
        let cname = const_name("hero", &e.id);
        out.push_str(&format!(
            "pub const {}_ABILITIES: &[AbilityId] = &[\n",
            cname,
        ));
        for ab_id in &e.abilities {
            let raw = ability_ids.get(ab_id.as_str()).unwrap_or_else(|| {
                panic!(
                    "hero '{}' references unknown ability '{}'",
                    e.id, ab_id
                )
            });
            out.push_str(&format!("\tAbilityId({}),\n", raw));
        }
        out.push_str("];\n");
    }
    out.push('\n');

    out.push_str(
        "pub fn hero_abilities(id: HeroId) -> &'static [AbilityId] {\n\tmatch id.0 {\n",
    );
    let mut next: u16 = 1;
    for e in entries {
        if !e.tombstone {
            let cname = const_name("hero", &e.id);
            out.push_str(&format!("\t\t{} => {}_ABILITIES,\n", next, cname));
        }
        next += 1;
    }
    out.push_str("\t\t_ => &[],\n\t}\n}\n\n");
}

fn emit_projectile_kinds(out: &mut String, entries: &[ProjKind]) {
    // No display_name for projectile kinds (they are visual kinds, not labels).
    let converted: Vec<Entry> = entries.iter().map(|p| Entry {
        id: p.id.clone(),
        display_name: String::new(),
        tombstone: p.tombstone,
    }).collect();
    emit_namespace(out, "ProjectileKind", "projectile", &converted, false);
}
