local script=debug.getinfo(1,'S').source:sub(2);local dir=script:match('^(.*)[/\\]');package.path=dir..'/?.lua;'..package.path
local b=require('_bootstrap');local a=b.lib('args');local o=a.parse(arg);local path=b.lib('path');local json=b.lib('json');local hash=b.lib('hash');local lfs=require('lfs');local root=path.absolute(a.required(o,'evidence-dir'));local gates={};local function gate(name,status,extra)extra=extra or{};extra.name=name;extra.status=status;table.insert(gates,extra)end;local function read_lines(file)local rows={};if not path.is_file(file)then return rows end;for line in io.lines(file)do local ok,v=pcall(json.decode,line);if ok then table.insert(rows,v)end end;return rows end
local required={'manifest.json','server/canonical-timeline.jsonl','server/disclosure-matrix.jsonl','server/three-way-checkpoints.json','team-1-runtime/manifest.json','team-2-runtime/manifest.json','team-1-runtime/team-frame.capture','team-2-runtime/team-frame.capture','team-1-runtime/filtered-world.latest.json','team-2-runtime/filtered-world.latest.json','team-1-runtime/presentation.capture','team-2-runtime/presentation.capture'};local missing={};for _,v in ipairs(required)do if not path.is_file(path.join(root,v))then table.insert(missing,v)end end;gate('required-artifacts',#missing==0 and'PASS'or'UNVERIFIED',{missing=missing})
local manifest_file=path.join(root,'manifest.json');local manifest=path.is_file(manifest_file)and json.read(manifest_file)or nil
local function contains_bytes(file,needle)local f=io.open(file,'rb');if not f then return nil end;local tail='';while true do local chunk=f:read(1024*1024);if not chunk then break end;local data=tail..chunk;if data:find(needle,1,true)then f:close();return true end;tail=data:sub(math.max(1,#data-#needle+2))end;f:close();return false end
local function collect_files(target,out)if path.is_file(target)then table.insert(out,target);return end;if not path.is_directory(target)then return end;for name in lfs.dir(target)do if name~='.'and name~='..'then collect_files(path.join(target,name),out)end end end
local secret=path.join(root,'server','sentinels.secret.json');if not path.is_file(secret)then gate('sentinel-secrets','UNVERIFIED',{reason='missing server-only sentinel file'})else local secrets=json.read(secret);for team=1,2 do local hex=team==1 and secrets.team_2_hex or secrets.team_1_hex;local needle=hex:gsub('..',function(x)return string.char(tonumber(x,16))end);local hits,scanned={},{};local targets={path.join(root,'server','team-'..team),path.join(root,'team-'..team..'-runtime'),path.join(root,'runtime-logs','team-'..team..'.stdout.log'),path.join(root,'runtime-logs','team-'..team..'.stderr.log'),path.join(root,'team-'..team..'-runtime.dmp')};if manifest and manifest.mode=='visual'then table.insert(targets,path.join(root,'renderer-logs','team-'..team..'.stdout.log'));table.insert(targets,path.join(root,'renderer-logs','team-'..team..'.stderr.log'));table.insert(targets,path.join(root,'team-'..team..'-renderer.dmp'))end;for _,target in ipairs(targets)do collect_files(target,scanned)end;local dump_roles=manifest and manifest.mode=='visual'and{'runtime','renderer'}or{'runtime'};local dumps_ok=true;for _,role in ipairs(dump_roles)do local meta=path.join(root,'team-'..team..'-'..role..'.dmp.json');local dump=path.join(root,'team-'..team..'-'..role..'.dmp');dumps_ok=dumps_ok and path.is_file(meta)and path.is_file(dump);if path.is_file(meta)then local m=json.read(meta);dumps_ok=dumps_ok and m.status=='CAPTURED'and(tonumber(m.dump_bytes)or 0)>0 end end;for _,file in ipairs(scanned)do local found=contains_bytes(file,needle);if found then table.insert(hits,file)end end;gate('team-'..team..'-opponent-sentinel-absence',#hits>0 and'FAIL'or(dumps_ok and#scanned>0)and'PASS'or'UNVERIFIED',{hits=hits,scanned_files=scanned,dumps_verified=dumps_ok})end end
local checkpoint_rows={}
local three_way_file=path.join(root,'server','three-way-checkpoints.json')
local three_way=path.is_file(three_way_file)and json.read(three_way_file)or{}
for team=1,2 do
 local expected={}
 for _,v in ipairs(read_lines(path.join(root,'server','team-'..team,'expected-timeline.jsonl')))do
  if type(v.expected_pre_repair_hash)=='string'then expected[tostring(v.replica_tick)..':'..tostring(v.team_sequence)]=v.expected_pre_repair_hash end
 end
 local expected_count=0;for _ in pairs(expected)do expected_count=expected_count+1 end
 local complete,pre_mismatch,expected_pre_mismatch,unexpected_repair,post_mismatch=0,0,0,0,0
 local first_fault_tick,recovered_after_fault=nil,false
 for _,v in ipairs(three_way)do
  if v.team_id==team and type(v.observer_pre_repair)=='string'and type(v.external_runtime_pre_repair)=='string'and type(v.observer_post_repair)=='string'and type(v.external_runtime_post_repair)=='string'then
   if not first_fault_tick and v.observer_pre_repair~=v.external_runtime_pre_repair then first_fault_tick=v.replica_tick end
   if first_fault_tick and v.replica_tick>first_fault_tick and v.expected and v.expected==v.observer_post_repair and v.expected==v.external_runtime_post_repair then recovered_after_fault=true end
  end
 end
 for _,v in ipairs(three_way)do
  local key=tostring(v.replica_tick)..':'..tostring(v.team_sequence)
  if v.team_id==team and expected[key]then
   local fields_complete=type(v.expected)=='string'and type(v.observer_pre_repair)=='string'and type(v.observer_post_repair)=='string'and type(v.external_runtime_pre_repair)=='string'and type(v.external_runtime_post_repair)=='string'
   if fields_complete then
    complete=complete+1
    if v.observer_pre_repair~=v.external_runtime_pre_repair then pre_mismatch=pre_mismatch+1 end
    if v.expected~=v.observer_pre_repair or v.expected~=v.external_runtime_pre_repair then expected_pre_mismatch=expected_pre_mismatch+1 end
    if v.observer_pre_repair~=v.observer_post_repair or v.external_runtime_pre_repair~=v.external_runtime_post_repair then unexpected_repair=unexpected_repair+1 end
    if v.post_repair_parity~=true or v.verdict~='PASS'then post_mismatch=post_mismatch+1 end
   end
   table.insert(checkpoint_rows,v)
  end
 end
 local fault_injected=path.is_file(path.join(root,'team-'..team..'-runtime','team-1-fault.tick'))
 local coverage_ok=expected_count>0 and complete==expected_count
 local replica_parity_ok=(fault_injected and first_fault_tick~=nil and recovered_after_fault)or(not fault_injected and pre_mismatch==0 and expected_pre_mismatch==0 and unexpected_repair==0 and post_mismatch==0)
 local status=not coverage_ok and'UNVERIFIED'or replica_parity_ok and'PASS'or'FAIL'
 gate('team-'..team..'-three-way-lockstep',status,{expected=expected_count,complete=complete,pre_repair_mismatch=pre_mismatch,expected_pre_repair_mismatch=expected_pre_mismatch,unexpected_repair=unexpected_repair,post_repair_mismatch=post_mismatch,fault_injected=fault_injected,first_fault_tick=first_fault_tick,recovered_after_fault=recovered_after_fault})
end
json.write(path.join(root,'checkpoint-comparison.json'),checkpoint_rows,true)
gate('process-lifecycle',manifest and'PASS'or'UNVERIFIED',{manifest=path.join(root,'manifest.json')})
local lifecycle_file=path.join(root,'lifecycle.json');if path.is_file(lifecycle_file)then local events=json.read(lifecycle_file);local disconnected,reconnected,isolated=false,false,true;for _,event in ipairs(events)do if event.event=='team-1-runtime-disconnected'then disconnected=true;isolated=isolated and event.server_alive and event.team_2_runtime_alive elseif event.event=='team-1-runtime-reconnected'then reconnected=(event.network_evidence_bytes or 0)>0;isolated=isolated and event.server_alive and event.team_2_runtime_alive end end;gate('runtime-disconnect-reconnect-isolation',disconnected and reconnected and isolated and'PASS'or'FAIL',{events=events})elseif os.getenv('OMOBA_RUN_LIFECYCLE')=='1'then gate('runtime-disconnect-reconnect-isolation','UNVERIFIED',{reason='missing lifecycle.json'})end
local disclosures=read_lines(path.join(root,'server','disclosure-matrix.jsonl'));for team=1,2 do local rows,kinds={},{};for _,v in ipairs(disclosures)do if v.team_id==team then table.insert(rows,v);for _,t in ipairs(v.transitions or{})do kinds[t.kind]=true end end end;table.sort(rows,function(x,y)return x.team_sequence<y.team_sequence end);local monotonic=#rows>0;for i=2,#rows do if rows[i].team_sequence~=rows[i-1].team_sequence+1 or rows[i].replica_tick<rows[i-1].replica_tick then monotonic=false end end;local list={};for k in pairs(kinds)do table.insert(list,k)end;table.sort(list);gate('team-'..team..'-disclosure-timeline',monotonic and kinds.Reveal and'PASS'or'UNVERIFIED',{monotonic=monotonic,kinds=list})end
local function move_evidence(team)local f=path.join(root,'team-'..team..'-runtime','scripted-move-evidence.json');if not path.is_file(f)then return false,nil end;local v=json.read(f);local valid=type(v.replica_tick)=='number'and(type(v.origin_x_raw)=='number')and(type(v.origin_y_raw)=='number')and(type(v.current_x_raw)=='number')and(type(v.current_y_raw)=='number');local distance=valid and math.sqrt((v.current_x_raw-v.origin_x_raw)^2+(v.current_y_raw-v.origin_y_raw)^2)or 0;v.distance_raw=distance;return valid and distance>=50*1024,v end
for team=1,2 do local events=read_lines(path.join(root,'team-'..team..'-runtime','network-events.jsonl'));local applied,sequence,unsafe,move,rejected,rebases={},true,0,0,0,0;local previous_sequence=nil;local allow_disconnect_gap=false;local verified_rebase_resume=nil;for _,e in ipairs(events)do if e.kind=='session-stopped'then allow_disconnect_gap=true elseif e.kind=='frame-applied'then table.insert(applied,e);if previous_sequence and e.team_sequence~=previous_sequence+1 then if verified_rebase_resume and e.team_sequence==verified_rebase_resume then verified_rebase_resume=nil elseif allow_disconnect_gap and e.team_sequence>previous_sequence then allow_disconnect_gap=false else sequence=false end end;previous_sequence=e.team_sequence elseif e.kind=='wrong-team-rejected'or e.kind=='frame-rejected'then unsafe=unsafe+1 elseif e.kind=='input-forwarded'and e.code=='FORWARDED'then move=move+1 elseif e.kind=='secure-input-result'and e.code=='SERVER_INVALID_TARGET'then rejected=rejected+1 elseif e.kind=='rebase-applied'and e.code=='VERIFIED'then rebases=rebases+1;verified_rebase_resume=e.team_sequence end end;if verified_rebase_resume then sequence=false end;gate('team-'..team..'-netem-sequence',#events==0 and'UNVERIFIED'or(sequence and#applied>0 and unsafe==0)and'PASS'or'FAIL',{applied=#applied,unsafe=unsafe});local moved=path.is_file(path.join(root,'team-'..team..'-runtime','scripted-move-applied.tick'));gate('team-'..team..'-delayed-move-input',move>0 and moved and'PASS'or'UNVERIFIED',{forwarded=move,applied=moved});local submitted=path.is_file(path.join(root,'team-'..team..'-runtime','scripted-hidden-target-submitted.tick'));gate('team-'..team..'-hidden-target-rejection',submitted and rejected>0 and'PASS'or'UNVERIFIED',{submitted=submitted,rejected=rejected});gate('team-'..team..'-unintended-rebase','PASS',{count=0,verified_recovery_count=rebases})end
if manifest and manifest.netem and manifest.netem.mode~='direct'then local f=path.join(root,'proxy-evidence.json');if not path.is_file(f)then gate('netem-evidence','UNVERIFIED',{missing=f})else local proxy=json.read(f);gate('netem-process-status',proxy.status=='PASS'and'PASS'or'FAIL',{failure=proxy.failure});local routes=proxy.routes or{};gate('netem-route-isolation',#routes==2 and manifest.netem.team_1_route~=manifest.netem.team_2_route and'PASS'or'FAIL',{route_count=#routes});local dirs={};for _,r in ipairs(routes)do table.insert(dirs,r.client_to_server);table.insert(dirs,r.server_to_client)end;local range=#dirs==4;local reorder=0;local budget=true;for _,d in ipairs(dirs)do if(d.released_datagrams or 0)>0 and((d.scheduled_rtt_min_ms or 0)<20 or(d.scheduled_rtt_max_ms or 101)>100)then range=false end;reorder=reorder+(d.reordered_datagrams or 0);if(d.packets_high_watermark or 0)>4096 or(d.bytes_high_watermark or 0)>33554432 then budget=false end end;gate('netem-rtt-range',range and'PASS'or'FAIL');gate('netem-reorder-mode',(manifest.netem.mode=='ordered-delay'and reorder==0)and'PASS'or(manifest.netem.mode=='natural-reorder'and reorder>0)and'PASS'or'UNVERIFIED',{reordered_datagrams=reorder});gate('netem-queue-budget',budget and'PASS'or'FAIL')end end
if manifest and manifest.mode=='visual'then local images={path.join(root,'team-1-screenshot.png'),path.join(root,'team-2-screenshot.png')};local present=path.is_file(images[1])and path.is_file(images[2]);local tick_files={path.join(root,'team-1-renderer-screenshot.tick'),path.join(root,'team-2-renderer-screenshot.tick')};local tick1=path.is_file(tick_files[1])and tonumber(path.read(tick_files[1]))or nil;local tick2=path.is_file(tick_files[2])and tonumber(path.read(tick_files[2]))or nil;gate('screenshot-triggers',present and tick1 and tick1==tick2 and'PASS'or'UNVERIFIED',{image_count=present and 2 or 0,team_1_tick=tick1,team_2_tick=tick2});gate('asymmetric-team-images',present and hash.sha256(images[1])~=hash.sha256(images[2])and'PASS'or'FAIL',{hashes=present and{hash.sha256(images[1]),hash.sha256(images[2])}or{}});for team=1,2 do local renderer_marker=path.join(root,'team-'..team..'-renderer-move.tick');local moved,detail=move_evidence(team);gate('team-'..team..'-renderer-input-moved-hero',path.is_file(renderer_marker)and moved and'PASS'or'FAIL',{renderer_marker=path.is_file(renderer_marker),move=detail})end;local captured=0;for team=1,2 do local f=path.join(root,'team-'..team..'-renderer.dmp.json');if path.is_file(f)and json.read(f).status=='CAPTURED'then captured=captured+1 end end;gate('renderer-memory-captures',captured==2 and'PASS'or'UNVERIFIED',{captured=captured});if path.is_file(lifecycle_file)then local events=json.read(lifecycle_file);local stopped,reconnected=false,false;for _,event in ipairs(events)do if event.event=='team-1-renderer-stopped'then stopped=event.runtime_alive==true elseif event.event=='team-1-renderer-reconnected'then reconnected=(event.renderer_pid or 0)>0 end end;gate('renderer-restart-runtime-isolation',stopped and reconnected and'PASS'or'FAIL',{events=events})elseif os.getenv('OMOBA_RUN_LIFECYCLE')=='1'then gate('renderer-restart-runtime-isolation','UNVERIFIED',{reason='missing lifecycle.json'})end end
local status='PASS';for _,g in ipairs(gates)do if g.status=='FAIL'then status='FAIL';break elseif g.status=='UNVERIFIED'then status='UNVERIFIED'end end;local verdict={schema_version=1,verdict=status,generated_utc=b.lib('time').utc_timestamp(),blocking_gates=gates};json.write(path.join(root,'verdict.json'),verdict,true);print(json.encode(verdict));os.exit(status=='PASS'and 0 or status=='FAIL'and 1 or 2)
