local script=debug.getinfo(1,'S').source:sub(2);local dir=script:match('^(.*)[/\\]');package.path=dir..'/?.lua;'..package.path
local b=require('_bootstrap');local path=b.lib('path');local hash=b.lib('hash');local lfs=require('lfs');local o=b.lib('args').parse(arg);local action=assert(o.action or o.positional[1],'--action required');local profile=o.profile or'debug';local root=b.root
local outputs={['script-dll']=path.join(root,'scripts','target',profile,'base_content.dll'),backend=path.join(root,'omb','target',profile,'omobab.exe'),frontend=path.join(root,'omfx','target',profile,'executor.exe')}
local roots={['script-dll']={'rust-toolchain.toml','scripts/script-abi','omoba-core','omoba-template-ids/src','omoba-sim','scripts/Cargo.toml','scripts/Cargo.lock','scripts/base_content'},backend={'rust-toolchain.toml','scripts/script-abi','omoba-core','omoba-template-ids/src','omoba-sim','specs/src','log4rs/src','omb/Cargo.toml','omb/Cargo.lock','omb/src'},frontend={'rust-toolchain.toml','scripts/script-abi','omoba-core','omoba-template-ids/src','omoba-sim','specs/src','log4rs/src','omfx/Cargo.toml','omfx/Cargo.lock','omfx/executor','omfx/game','third_party/fyrox-impl-1.0.1/src'}};if profile=='release'then for _,set in pairs(roots)do table.insert(set,'scripts/lua_data')end end;if o.output or o.input then assert(o.output and o.input,'--output and --input must be used together');outputs.fixture=path.absolute(o.output);roots.fixture={path.absolute(o.input)}end
local function newest(p)local a=lfs.attributes(p);assert(a,'input missing: '..p);if a.mode=='file'then return a.modification,p end;local best,name=0,p;for n in lfs.dir(p)do if n~='.'and n~='..'then local t,f=newest(path.join(p,n));if t>best then best,name=t,f end end end;return best,name end
local function copy(source,dest)local input=assert(io.open(source,'rb'));local bytes=input:read('a');input:close();path.write(dest,bytes,true,true);local a=lfs.attributes(source);lfs.touch(dest,a.access,a.modification)end
local function stage(source,dest,label)assert(path.is_file(source),'source missing: '..source);if path.is_file(dest)and lfs.attributes(dest,'modification')>=lfs.attributes(source,'modification')and hash.sha256(source)==hash.sha256(dest)then print('fresh: '..label..' is up-to-date');return 0 end;copy(source,dest);print('staged: '..label);return 0 end
if action=='stage-dll'then os.exit(stage(outputs['script-dll'],path.join(root,'scripts','base_content.dll'),'base_content.dll ('..profile..')'))elseif action=='stage-backend-spawn'then os.exit(stage(path.join(root,'omb','target','release','omobab.exe'),path.join(root,'omb','target','debug','omobab.exe'),'release backend spawn copy'))end
assert(action=='check','unknown action: '..action);local artifact=assert(o.artifact,'--artifact required');local output=assert(outputs[artifact],'unknown artifact: '..artifact);if not path.is_file(output)then print('stale: '..artifact..' output missing: '..output);os.exit(1)end;local latest,which=0,'';for _,relative in ipairs(roots[artifact])do local candidate=path.is_absolute(relative)and relative or path.join(root,relative);local t,f=newest(candidate);if t>latest then latest,which=t,f end end;if latest>lfs.attributes(output,'modification')then print('stale: '..artifact..' input newer than output: '..which);os.exit(1)end;print('fresh: '..artifact..' output is up-to-date: '..output)
