local script=debug.getinfo(1,'S').source:sub(2);local dir=script:match('^(.*)[/\\]');package.path=dir..'/?.lua;'..package.path
local b=require('_bootstrap');local path=b.lib('path');local toml=b.lib('toml');local root=b.root;local config_path=path.absolute(os.getenv('OMB_GAME_TOML')or path.join(root,'omb','game_stress.toml'));local config=path.exists(config_path)and toml.read(config_path)or{};local server=config.server or{};local content=config.content or{};local stress=config.stress or{}
local function setting(env,key,default,convert)local value=os.getenv(env);if not value or value==''then value=stress[key];if value==nil then value=default end end;return convert(value)end
local function boolean(v)if type(v)=='boolean'then return v end;v=tostring(v):lower();return v~='0'and v~='false'and v~='no'and v~='off'end
local creeps=setting('OMOBA_STRESS_CREEPS','CREEPS',2000,tonumber);local towers=setting('OMOBA_STRESS_TOWERS','TOWERS',1000,tonumber);local spacing=setting('OMOBA_STRESS_TOWER_SPACING','TOWER_SPACING',50,tonumber);local interval=setting('OMOBA_STRESS_SPAWN_INTERVAL','SPAWN_INTERVAL',0.001,tonumber);local direct=setting('OMOBA_STRESS_DIRECT_CREEPS','DIRECT_CREEPS',true,boolean)
local story=tostring(server.STORY or'TD_STRESS');local data_dir=tostring(content.STORY_DATA_DIR or'../scripts/lua_data');if not path.is_absolute(data_dir)then data_dir=path.join(path.parent(config_path),data_dir)end;local output=path.join(data_dir,story,'map.lua')
local points={};for _,c in ipairs({{-1340,1340,-740,-260},{-1340,1340,-140,340},{-1340,1340,460,740}})do local x=c[1];while x<=c[2]and#points<towers do local y=c[3];while y<=c[4]and#points<towers do if x*x+y*y>=62500 then table.insert(points,{x,y})end;y=y+spacing end;x=x+spacing end end;assert(#points>=towers,'Grid容量不夠')
local route={{-1400,-800},{1400,-800},{1400,-200},{-1400,-200},{-1400,400},{1400,400},{1400,800},{-1400,800}};local segments,total={},0;for i=1,#route-1 do local a,c=route[i],route[i+1];local length=math.sqrt((c[1]-a[1])^2+(c[2]-a[2])^2);table.insert(segments,{i,a,c,length});total=total+length end
local initial={};if direct then for i=0,creeps-1 do local d=((i+0.5)/math.max(creeps,1))*total;local acc=0;for _,s in ipairs(segments)do if d<=acc+s[4]then local t=(d-acc)/s[4];table.insert(initial,{Creep='td_stress',Path='td_main',PathIndex=s[1],X=math.floor((s[2][1]+(s[3][1]-s[2][1])*t)*1000+0.5)/1000,Y=math.floor((s[2][2]+(s[3][2]-s[2][2])*t)*1000+0.5)/1000});break end;acc=acc+s[4]end end end
local waves={};if not direct then local entries={};for i=0,creeps-1 do table.insert(entries,{Time=math.floor(i*interval*1000+0.5)/1000,Creep='td_stress'})end;waves={{Name='W_STRESS',StartTime=0.0,Detail={{Path='td_main',Creeps=entries}}}}end
local structures={};for i,p in ipairs(points)do table.insert(structures,{Tower=(i-1)%2==0 and'tower_ice'or'tower_bomb',Faction='Player',X=p[1]+0.0,Y=p[2]+0.0,IsBase=false})end
local data={GameMode='TowerDefense',Path={{Name='td_main',Points={'td_spawn','td_cp1','td_cp2','td_cp3','td_cp4','td_cp5','td_cp6','td_exit'}}},Creep={{Name='td_stress'}},CheckPoint={{Name='td_spawn',Class='Spawn',X=-1400.0,Y=-800.0},{Name='td_cp1',Class='Path',X=1400.0,Y=-800.0},{Name='td_cp2',Class='Path',X=1400.0,Y=-200.0},{Name='td_cp3',Class='Path',X=-1400.0,Y=-200.0},{Name='td_cp4',Class='Path',X=-1400.0,Y=400.0},{Name='td_cp5',Class='Path',X=1400.0,Y=400.0},{Name='td_cp6',Class='Path',X=1400.0,Y=800.0},{Name='td_exit',Class='Base',X=-1400.0,Y=800.0}},Tower={},InitialCreeps=initial,Structures=structures,CreepWave=waves,BlockedRegions={}}
local function quote(v)return'"'..v:gsub('\\','\\\\'):gsub('"','\\"')..'"'end;local function encode(v,indent)local kind=type(v);if kind=='string'then return quote(v)elseif kind=='number'then return tostring(v)elseif kind=='boolean'then return tostring(v)elseif kind=='nil'then return'nil'end;local pad=string.rep('  ',indent);local child=string.rep('  ',indent+1);local keys={};local array=#v>0;if array then for i=1,#v do table.insert(keys,i)end else for k in pairs(v)do table.insert(keys,k)end;table.sort(keys)end;if#keys==0 then return'{}'end;local lines={'{'};for _,k in ipairs(keys)do local prefix=array and''or(k:match('^[%a_][%w_]*$')and k or'['..quote(k)..']')..' = ';table.insert(lines,child..prefix..encode(v[k],indent+1)..',')end;table.insert(lines,pad..'}');return table.concat(lines,'\n')end
local rendered='return function(ctx)\n  return '..encode(data,1)..'\nend\n';local action='unchanged';if not path.exists(output)or path.read(output)~=rendered then path.write(output,rendered,true);action='wrote'end;print(string.format('%s %s  towers=%d  initial_creeps=%d  wave_creeps=%d',action,output,#structures,#initial,direct and 0 or creeps))
